### ISSUE TITLE
Deploy v1.0.0

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#1]
### Tasks
- [x] [[liblouis/liblouis-nar#2] Release version 2.6.3](https://github.com/liblouis/liblouis-nar/pull/2) (@bertfrees)
- [x] [[liblouis/liblouis-java#5] Release 1.4.0 with lou_findTable feature](https://github.com/liblouis/liblouis-java/pull/5) (@bertfrees)
- [x] [[jStyleParser#] Apply patches to version 1.20](https://github.com/snaekobbi/jStyleParser/pull/3) (@bertfrees)
- [x] [[braille-css#1] Release version 1.0.0](https://github.com/snaekobbi/braille-css/pull/1) (@bertfrees)
- [x] [[daisy/pipeline-build-utils#22] Release pax-exam-helper 1.9.1](https://github.com/daisy/pipeline-build-utils/pull/22) (@bertfrees)
- [x] [[pipeline-mod-braille#45] DTBook to PEF script](https://github.com/snaekobbi/pipeline-mod-braille/issues/45) (@bertfrees)
- [x] [[daisy/pipeline-mod-braille#31] Release version 1.9.1](https://github.com/daisy/pipeline-mod-braille/issues/31) (@bertfrees)
- [x] [[daisy/pipeline-assembly#78] Release version 1.9.1](https://github.com/daisy/pipeline-assembly/issues/78) (@bertfrees)
- [x] [[pipeline-mod-celia#1] Release version 1.0.0](https://github.com/snaekobbi/pipeline-mod-celia/issues/1) (@bertfrees)
- [x] [[pipeline-mod-nota#1] Release version 1.0.0](https://github.com/snaekobbi/pipeline-mod-nota/issues/1) (@bertfrees)
- [x] [[pipeline-mod-nlb#1] Release version 1.0.0](https://github.com/snaekobbi/pipeline-mod-nlb/issues/1) (@bertfrees)
- [x] [[pipeline-mod-mtm#1] Release version 1.0.0](https://github.com/snaekobbi/pipeline-mod-mtm/issues/1) (@bertfrees)
- [x] [[pipeline-mod-dedicon#1] Release version 1.0.0](https://github.com/snaekobbi/pipeline-mod-dedicon/issues/1) (@bertfrees)
- [x] [[pipeline-mod-sbs#1] Release version 1.0.0](https://github.com/snaekobbi/pipeline-mod-sbs/issues/1) (@bertfrees)
- [x] [[issues#15] Ansible script for provisioning of test server](https://github.com/snaekobbi/issues/issues/15) (@bertfrees)
- [x] [[system#1] Release version 1.0.0](https://github.com/snaekobbi/system/issues/1) (@bertfrees)
- [x] [[issues#11] Install Pipeline version 1.9.1 on test server](https://github.com/snaekobbi/issues/issues/11) (@bertfrees + @josteinaj)

Total: 8h
