### ISSUE TITLE
Deploy v1.1.0

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#101]
### Tasks
- [x] [[system#2] System should start up properly each time](https://github.com/snaekobbi/system/issues/2) (@bertfrees)
- [ ] [[daisy/pipeline-assembly#79] Fix service pipeline2-webuid stop](https://github.com/daisy/pipeline-assembly/issues/79)
- [x] [[issues#16] Use Ansible script to update test server](https://github.com/snaekobbi/issues/issues/16) (@josteinaj)
- [x] [[jStyleParser#4] Release version 1.20-p2](https://github.com/snaekobbi/jStyleParser/issues/4) (@bertfrees)
- [x] [[braille-css#3] Release version 1.1.0](https://github.com/snaekobbi/braille-css/pull/3) (@bertfrees)
- [x] [[daisy/pipeline-mod-braille#32] Release version 1.9.2](https://github.com/daisy/pipeline-mod-braille/pull/32) (@bertfrees)
- [x] [[daisy/pipeline-assembly#81] Release version 1.9.2](https://github.com/daisy/pipeline-assembly/pull/81) (@bertfrees)
- [x] [[pipeline-mod-nlb#3] Release version 1.1.0](https://github.com/snaekobbi/pipeline-mod-nlb/pull/3) (@bertfrees)
- [x] [[system#6] Release version 1.1.0](https://github.com/snaekobbi/system/pull/6) (@bertfrees)
- [x] Install new version on test server

**Comment by bertfrees** [comment]
Installed with `test-server shellcmd pipeline-upgrade`
