### ISSUE TITLE
[4.3:34] The system shall support the braille code used in Denmark, Finland, Norway, Sweden, Switzerland and the Netherlands for uncontracted braille.

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#102]
### Requirements
- [[4.3:34]](http://snaekobbi.github.io/requirements#4.3:34) The system shall support the braille code used in Denmark, Finland, Norway, Sweden and Switzerland for uncontracted braille.
- [[4.3:34C]](http://snaekobbi.github.io/requirements#4.3:34C) The system shall support the braille code used in the Netherlands for uncontracted braille.
### Tasks
- [x] provide test data
  - [x] Swedish (@JC-MTM)
  - [x] Danish (@stesk)
  - [x] Dutch (@dkager)
- [ ] execute system tests
  - [x] German (@mixa72 1hr) ![FAIL](http://snaekobbi.github.io/sprints/FAIL.svg)
  - [x] Swedish (@JC-MTM 2hr) ![PASS](http://snaekobbi.github.io/sprints/PASS.svg)
  - [ ] Finnish (@paivis 2hr) ![Ready for test](http://snaekobbi.github.io/sprints/Ready_for_test.svg)
  - [x] Norwegian (@KariRudjord 2hr) ![FAIL](http://snaekobbi.github.io/sprints/FAIL.svg)
  - [x] Danish (@stesk 2h) ![PASS](http://snaekobbi.github.io/sprints/PASS.svg)
  - [x] Dutch (@dkager 2h) ![PASS](http://snaekobbi.github.io/sprints/PASS.svg)
### Test results
- [SE](https://github.com/snaekobbi/testing/blob/master/Test%20protocol/Sprint_2/SE/System%20Test%20protocol_Braille%20DP2_Sprint%202_SE.xlsx?raw=true)
- [DK](https://github.com/snaekobbi/testing/blob/master/Test%20protocol/Sprint_2/DK/System%20Test%20protocol_Braille%20DP2_Sprint%202_DK.xlsx?raw=true): Marking of capital letters is generally not used at Nota (beyond acronyms and Roman numerals), so we must be able to disable this feature. Special inline markup (emphasis, acronyms) is not supported, it seems. However, I believe this is part of another requirement, so I have not taken these features into account here.
- [DE](https://github.com/snaekobbi/testing/blob/master/Test%20protocol/Sprint_2/DE/System%20Test%20protocol_Braille%20DP2_Sprint%202_DE.xlsx?raw=true): Job does not end (Running ...). No output.
- [NL](https://github.com/snaekobbi/testing/blob/master/Test%20protocol/Sprint_2/NL/System%20Test%20protocol_Braille%20DP2_Sprint%202_NL.xlsx?raw=true)
- NO
  - Most signs seems to be correct, letters, numbers, punktuation marks and capitals
  - roman numerals containing of more than one letter e.g. Henry IV, shall accoring to norwegian standard have only one dot 6 before ( 6 is capital sign. In the test there is two dot 6. this is correct for ordinary text in capitals but not for roman numbers). I'm not sure if the rule is possible to automate?
  - sami letters: a with accute in sami is 12356. s with inverted cirkumfleks in sami is 156
  - old norse: é i old norse is 2346. thorn in old norse is 1246. oe (æ) i old norse is 346. If there is a conflict between sami and old norse letters, it is more important that the sami letters works.
  - some of the diacritics appear strange. Before I check them more I would like to know if you are working on it.
#### Issues
- [ ] [[daisy/pipeline-webui#26] Job page keeps showing "Running..."](https://github.com/daisy/pipeline-webui/issues/26)
- [ ] Performance issue in SBS translator?
- [ ] [[daisy/pipeline-mod-braille#38] Fix XSLT warnings that looks like errors](https://github.com/daisy/pipeline-mod-braille/issues/38)
