### ISSUE TITLE
[4.3:37] The system shall support the braille code used in Denmark, Norway, Sweden and Switzerland for contracted braille.

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#104]
### Requirement

[[4.3:37]](http://snaekobbi.github.io/requirements#4.3:37) The system shall support the braille code used in Denmark, Norway, Sweden and Switzerland for contracted braille.
### Tasks
- [x] update requirements: [[requirements#6] Tests for Norwegian translation](https://github.com/snaekobbi/requirements/pull/6) (@bertfrees)
- [x] integration of latest Norwegian tables (@bertfrees 1h) (https://github.com/snaekobbi/pipeline-mod-nlb/commit/ad58fad2358e371b456856fd50fa7dac5472b6fd)
- [x] provide test data: Norwegian (@KariRudjord)
- [ ] execute system tests
  - [x] German (@mixa72 1hr) ![FAIL](http://snaekobbi.github.io/sprints/FAIL.svg)
  - [x] Danish (@stesk 3h) ![PASS](http://snaekobbi.github.io/sprints/PASS.svg)
  - [ ] Norwegian (@KariRudjord) ![Ready for test](http://snaekobbi.github.io/sprints/Ready_for_test.svg)
### Test results
- [DE](https://github.com/snaekobbi/testing/blob/master/Test%20protocol/Sprint_2/DE/System%20Test%20protocol_Braille%20DP2_Sprint%202_DE.xlsx?raw=true): Job does not end (Running ...). No output.
- [DK](https://github.com/snaekobbi/testing/blob/master/Test%20protocol/Sprint_2/DK/System%20Test%20protocol_Braille%20DP2_Sprint%202_DK.xlsx?raw=true): Things look good in general. However, the marking of capital letters causes some mistranslations to occur; e.g., if a sentence starts with the very common word "Det", it will be translated as \d§ (three cells: indicator, letter d, "et" contraction) rather than è (single-cell contraction of "det"). Also, once again, markup-level semantics have not been tested.
#### Issues
- [ ] [[daisy/pipeline-webui#26] Job page keeps showing "Running..."](https://github.com/daisy/pipeline-webui/issues/26)
- [ ] Performance issue in SBS translator?
- [ ] [[daisy/pipeline-mod-braille#38] Fix XSLT warnings that looks like errors](https://github.com/daisy/pipeline-mod-braille/issues/38)
