### ISSUE TITLE
[4.3:41] The system shall be able to perform automatic hyphenation for uncontracted and contracted braille.

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#105]
### Requirement

[[4.3:41]](http://snaekobbi.github.io/requirements#4.3:41) The system shall be able to perform automatic hyphenation for uncontracted and contracted braille.
### Tasks
- [x] provide test data
  - [x] Danish (@stesk)
  - [x] Swedish (@JC-MTM)
  - [x] Finnish (@paivis)
  - [x] Dutch (@dkager)
- [ ] execute system tests
  - [x] German (@mixa72 2hr) ![FAIL](http://snaekobbi.github.io/sprints/FAIL.svg)
  - [x] Danish (@stesk 2hr) ![PASS](http://snaekobbi.github.io/sprints/PASS.svg)
  - [x] Swedish (@JC-MTM 2hr) ![FAIL](http://snaekobbi.github.io/sprints/FAIL.svg)
  - [ ] Finnish (@paivis 3hr) ![Ready for test](http://snaekobbi.github.io/sprints/Ready_for_test.svg)
  - [ ] Norwegian (@KariRudjord) ![Ready for test](http://snaekobbi.github.io/sprints/Ready_for_test.svg)
  - [x] Dutch (@dkager 2hr) ![PASS](http://snaekobbi.github.io/sprints/PASS.svg)
### Test results
- [SE](https://github.com/snaekobbi/testing/blob/master/Test%20protocol/Sprint_2/SE/System%20Test%20protocol_Braille%20DP2_Sprint%202_SE.xlsx?raw=true): No hyphenation: no word has been hyphenated, words are simple cut when row is finished.
- [DK](https://github.com/snaekobbi/testing/blob/master/Test%20protocol/Sprint_2/DK/System%20Test%20protocol_Braille%20DP2_Sprint%202_DK.xlsx?raw=true): Errors in grade 1: Sto-ckholm (should be Stock-holm); in grade 2: sel-vironi (should be selv-ironi). Otherwise everything looks good. Note that there are edge cases involving hyphenation and grade 2 which require further testing.
- [DE](https://github.com/snaekobbi/testing/blob/master/Test%20protocol/Sprint_2/DE/System%20Test%20protocol_Braille%20DP2_Sprint%202_DE.xlsx?raw=true): Job does not end (Running ...). No output.
- [NL](https://github.com/snaekobbi/testing/blob/master/Test%20protocol/Sprint_2/NL/System%20Test%20protocol_Braille%20DP2_Sprint%202_NL.xlsx?raw=true): Setting (unrealistically) low page width leads to words being hyphenated in odd places; regular page width is fine.
#### Issues
- [x] [[daisy/pipeline-mod-braille#33] hyphens:auto does't work](https://github.com/daisy/pipeline-mod-braille/issues/33)
- [ ] [[daisy/pipeline-webui#26] Job page keeps showing "Running..."](https://github.com/daisy/pipeline-webui/issues/26)
- [ ] Performance issue in SBS translator?
- [ ] [[daisy/pipeline-mod-braille#38] Fix XSLT warnings that looks like errors](https://github.com/daisy/pipeline-mod-braille/issues/38)
- [ ] [[daisy/pipeline-mod-braille#43] Lines are broken in the middle of words when Dotify translator is used](https://github.com/daisy/pipeline-mod-braille/issues/43)
- [ ] [[daisy/pipeline-mod-braille#44] Support hyphenation in dotify:translate](https://github.com/daisy/pipeline-mod-braille/issues/44)
