### ISSUE TITLE
[4.4:46] The system shall have support for top, right, bottom and left margins on blocks.

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#106]
### Requirement

[[4.4:46]](http://snaekobbi.github.io/requirements#4.4:46) The system shall have support for top, right, bottom and left margins on blocks.
### Tasks
- [x] ~~finalise requirement (@bertfrees)~~
- [x] provide test data (@mixa72, @JC-MTM)
- [x] execute system tests
  - [x] @mixa72 ![PASS](http://snaekobbi.github.io/sprints/PASS.svg)
  - [x] @JC-MTM ![FAIL](http://snaekobbi.github.io/sprints/FAIL.svg)
### Test results
- [DE](https://github.com/snaekobbi/testing/blob/master/Test%20protocol/Sprint_2/DE/System%20Test%20protocol_Braille%20DP2_Sprint%202_DE.xlsx?raw=true)
- [SE](https://github.com/snaekobbi/testing/blob/master/Test%20protocol/Sprint_2/SE/System%20Test%20protocol_Braille%20DP2_Sprint%202_SE.xlsx?raw=true): We cannot make the CSS work
