### ISSUE TITLE
[4.4:47] The system shall have support for top, right, bottom and left borders and padding on blocks.

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#107]
### Requirement

[[4.4:47]](http://snaekobbi.github.io/requirements#4.4:47) The system shall have support for top, right, bottom and left borders and padding on blocks.
### Tasks
- [x] finalise requirement: [[requirements#15] Tests for borders](https://github.com/snaekobbi/requirements/pull/15) (@bertfrees)
- [x] provide test data (@mixa72, @JC-MTM)
- [x] execute system tests
  - [x] @mixa72 ![FAIL](http://snaekobbi.github.io/sprints/FAIL.svg)
  - [x] @JC-MTM ![FAIL](http://snaekobbi.github.io/sprints/FAIL.svg)
### Test results
- [DE](https://github.com/snaekobbi/testing/blob/master/Test%20protocol/Sprint_2/DE/System%20Test%20protocol_Braille%20DP2_Sprint%202_DE.xlsx?raw=true)
  - css-specifications for border-top and border-bottom are ignored (no border in the output)
  - css-specifications for padding-right and margin-right are ignored
- [SE](https://github.com/snaekobbi/testing/blob/master/Test%20protocol/Sprint_2/SE/System%20Test%20protocol_Braille%20DP2_Sprint%202_SE.xlsx?raw=true)
  - No borders, although we tried to make the CSS work.
  - Padding: preceeding empty line before parapraphs that should have only indentation
#### Issues
- [ ] [[daisy/pipeline-mod-braille#45] Support dot pattern '⠒' in Dotify based formatter](https://github.com/daisy/pipeline-mod-braille/issues/45)
- [ ] [[daisy/pipeline-mod-braille#42] margin-right and padding-right broken](https://github.com/daisy/pipeline-mod-braille/issues/42)
