### ISSUE TITLE
[4.4:52] Besides left-aligned text, the system shall have support for centered and right-aligned text.

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#109]
### Requirement

[[4.4:52]](http://snaekobbi.github.io/requirements#4.4:52) Besides left-aligned text, the system shall have support for centered and right-aligned text.
### Tasks
- [ ] finalise requirement: [[requirements#49] Tests for text alignment](https://github.com/snaekobbi/requirements/issues/49)
- [x] provide test data (@mixa72, @JC-MTM)
- [ ] execute system tests
  - [x] @mixa72 ![FAIL](http://snaekobbi.github.io/sprints/FAIL.svg)
  - [ ] @JC-MTM ![Ready for test](http://snaekobbi.github.io/sprints/Ready_for_test.svg)
### Test results
- [DE](https://github.com/snaekobbi/testing/blob/master/Test%20protocol/Sprint_2/DE/System%20Test%20protocol_Braille%20DP2_Sprint%202_DE.xlsx?raw=true): left-aligned text is not completely left (wrong indent of 2 cells); centered is ok, right-aligned is ok
- [SE](https://github.com/snaekobbi/testing/blob/master/Test%20protocol/Sprint_2/SE/System%20Test%20protocol_Braille%20DP2_Sprint%202_SE.xlsx?raw=true): We have not succeeded in testing centered and right aligned text.
#### Issues
- [ ] [[daisy/pipeline-mod-braille#40] Default style sheets should be more basic](https://github.com/daisy/pipeline-mod-braille/issues/40)
