### ISSUE TITLE
[4.3:34] The system shall support the braille code used in Denmark, Finland, Norway, Sweden, Switzerland and the Netherlands for uncontracted braille.

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#11]
### Requirements
- [[4.3:34]](http://snaekobbi.github.io/requirements#4.3:34) The system shall support the braille code used in Denmark, Finland, Norway, Sweden and Switzerland for uncontracted braille.
- [[4.3:34C]](http://snaekobbi.github.io/requirements#4.3:34C) The system shall support the braille code used in the Netherlands for uncontracted braille.
### Tasks
- [x] update requirements (@bertfrees)
  - [ ] [[requirements#3] Tests for Danish translation](https://github.com/snaekobbi/requirements/issues/3)
  - [x] [[requirements#4] Tests for Finnish translation](https://github.com/snaekobbi/requirements/pull/4)
  - [x] [[requirements#5] Tests for Swedish translation](https://github.com/snaekobbi/requirements/pull/5)
  - [x] [[requirements#6] Tests for Norwegian translation](https://github.com/snaekobbi/requirements/pull/6)
  - [ ] [[requirements#7] Tests for German (Swiss) translation](https://github.com/snaekobbi/requirements/issues/7)
  - [x] [[requirements#42] Tests for Dutch translation](https://github.com/snaekobbi/requirements/issues/42)
- [x] integration (@bertfrees 4h)
  - [x] [[issues#12] Pipeline braille module per agency](https://github.com/snaekobbi/issues/issues/12)
  - [x] [[issues#14] Higher level translator components for all languages](https://github.com/snaekobbi/issues/issues/14)
  - [x] [[issues#13] Integrate latest liblouis tables](https://github.com/snaekobbi/issues/issues/13)
- [ ] provide test data
  - [x] German (@mixa72)
  - [ ] Swedish (@joeha480 1hr)
  - [x] Finnish (@paivis 2hr)
  - [x] Norwegian (@KariRudjord 2hr)
- [x] execute system tests
  - [x] German (@mixa72) ![FAIL](http://snaekobbi.github.io/sprints/FAIL.svg)
  - [ ] Swedish (@joeha480 1hr) ![Ready for test](http://snaekobbi.github.io/sprints/Ready_for_test.svg)
  - [ ] Finnish (@paivis 2hr) ![Ready for test](http://snaekobbi.github.io/sprints/Ready_for_test.svg)
  - [ ] Norwegian (@KariRudjord 2hr) ![Ready for test](http://snaekobbi.github.io/sprints/Ready_for_test.svg)
### Test results
- [System Test protocol_Braille DP2 v1.0_DE.xlsx
  ](https://github.com/snaekobbi/testing/blob/master/Test%20protocol/Sprint_1
  /DE/System%20Test%20protocol_Braille%20DP2%20v1.0_DE.xlsx?raw=true)
#### Issues
- [x] [[system#2] System should start up properly each time](https://github.com/snaekobbi/system/issues/2)
- [ ] [[daisy/pipeline-webui#26] Job page keeps showing "Running..."](https://github.com/daisy/pipeline-webui/issues/26)
