### ISSUE TITLE
[4.4:53] The system shall support block alignment relative to a vertical position on the page.

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#110]
### Requirement

[[4.4:53]](http://snaekobbi.github.io/requirements#4.4:53) The system shall support block alignment relative to a vertical position on the page.
### Tasks
- [x] finalise requirement: [[requirements#16] Tests for vertical positioning](https://github.com/snaekobbi/requirements/pull/16) (@bertfrees)
- [x] specification: [[braille-css-spec#20] Vertical positioning](https://github.com/snaekobbi/braille-css-spec/issues/20) (@bertfrees)
- [x] implementation: [[pipeline-mod-braille#28] Support vertical positioning](https://github.com/snaekobbi/pipeline-mod-braille/issues/28) (@bertfrees 8h)
- [x] provide test data (@mixa72, @JC-MTM)
- [ ] execute system tests
  - [x] @mixa72 ![PASS](http://snaekobbi.github.io/sprints/PASS.svg)
  - [ ] @JC-MTM ![Ready for test](http://snaekobbi.github.io/sprints/Ready_for_test.svg)
### Test results
- [DE](https://github.com/snaekobbi/testing/blob/master/Test%20protocol/Sprint_2/DE/System%20Test%20protocol_Braille%20DP2_Sprint%202_DE.xlsx?raw=true)
- [SE](https://github.com/snaekobbi/testing/blob/master/Test%20protocol/Sprint_2/SE/System%20Test%20protocol_Braille%20DP2_Sprint%202_SE.xlsx?raw=true): We have not succeeded in testing vertical position.
