### ISSUE TITLE
[4.4:54] The system shall by default handle whitespace characters in the source XML according to the following rules…

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#111]
### Requirement

[[4.4:54]](http://snaekobbi.github.io/requirements#4.4:54) The system shall by default handle whitespace characters (spaces, tabs, line feeds) in the source XML according to the following rules:
- Comments are removed entirely and do not affect whitespace handling.
- All whitespace surrounding block elements is removed.
- Leading and trailing whitespace inside block elements are removed.
- Sequences of whitespace characters are reduced to a single space character. Newline characters are handled as other whitespace.
### Tasks
- [x] finalise requirement: [[requirements#17] Tests for white space handling](https://github.com/snaekobbi/requirements/pull/17) (@bertfrees)
- [x] provide test data
  - [x] @dkager
  - [x] @KariRudjord
- [ ] execute system tests
  - [x] @dkager ![PASS](http://snaekobbi.github.io/sprints/PASS.svg)
  - [ ] @KariRudjord ![Ready for test](http://snaekobbi.github.io/sprints/Ready_for_test.svg)

**Comment by josteinaj** [comment]
@KariRudjord test filter in outlook for this notification

**Comment by josteinaj** [comment]
@KariRudjord another test for filter in outlook for this notification
