### ISSUE TITLE
Deploy v1.1.1 (bugfix release)

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#112]
### Tasks
- [x] [[daisy/pipeline-mod-braille#33] hyphens:auto does't work](https://github.com/daisy/pipeline-mod-braille/issues/33)
- [x] [[daisy/pipeline-mod-braille#35] Coding error in LiblouisTranslator](https://github.com/daisy/pipeline-mod-braille/issues/35)
- [x] [[braille-css#4] Release version 1.1.1](https://github.com/snaekobbi/braille-css/pull/4)
- [x] [[daisy/pipeline-mod-braille#37] Release version 1.9.3](https://github.com/daisy/pipeline-mod-braille/pull/37)
- [x] [[daisy/pipeline-assembly#82] Release version 1.9.3](https://github.com/daisy/pipeline-assembly/pull/82)
- [x] [[system#7] Release version 1.1.1](https://github.com/snaekobbi/system/pull/7)
- [x] Install new version on test server
