### ISSUE TITLE
sprint#3

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#113]
### General comments
- The first iteration is planned to end with an update of the test server on Monday 14/9 night. Based on the test results and whether developers have finished their work, there may be a second iteration.
- Features can be tested as soon as they are in state "Ready for test".
- During this sprint we are also going to prepare the requirements of features that will possibly be included in the next sprint. The features I'd like to focus on are all pagination-related features (page breaking, page layout, page numbering, etc.).
### Tasks

![priority:1](http://snaekobbi.github.io/sprints/priority_1.svg)
- [ ] Better script documentation (@bertfrees is creating a web site for this)
- [x] Implement an alternative conversion path based on the Dotify "TaskSystem", initially only for MTM (@joeha480, @bertfrees)
  - [x] [[daisy/pipeline-mod-braille#39] Adds an XML to OBFL step using Dotify](https://github.com/daisy/pipeline-mod-braille/pull/39)
  - [x] [[pipeline-mod-mtm#2] Add custom mtm:dtbook-to-pef script that uses dotify:xml-to-pef directly](https://github.com/snaekobbi/pipeline-mod-mtm/issues/2)
- [ ] Solve performance issues. The test server currently needs to be restarted often because it is not responding.
- [ ] Improve German and Norwegian translation (@egli, @usama49, @bertfrees, see [sub-issues](https://github.com/snaekobbi/sprints/milestones/sprint%233))
- [x] Re-execute tests after resolving other possible issues (@snaekobbi/testers, see [sub-issues](https://github.com/snaekobbi/sprints/milestones/sprint%233))
- [x] Implement and test support for line spacing (@jukkae,@bertfrees, @snaekobbi/testers, see [sub-issues](https://github.com/snaekobbi/sprints/milestones/sprint%233))

![priority:2](http://snaekobbi.github.io/sprints/priority_2.svg)
- [x] Changes to script options (@bertfrees)
  - [x] [[daisy/pipeline-mod-braille#34] Remove default-stylesheet option to avoid confusion](https://github.com/daisy/pipeline-mod-braille/issues/34)
  - [x] [[daisy/pipeline-mod-braille#46] Add "stylesheet" option](https://github.com/daisy/pipeline-mod-braille/issues/46)
- [x] Prepare requirements for sprint#4 (@snaekobbi/experts)
- [x] Continue work on [[daisy/pipeline-webui#23] Re-running jobs](https://github.com/daisy/pipeline-webui/issues/23) (@josteinaj)

![priority:3](http://snaekobbi.github.io/sprints/priority_3.svg)
- [ ] Various other improvements to web interface
  - [ ] [[daisy/pipeline-webui#26] Job page keeps showing "Running..."](https://github.com/daisy/pipeline-webui/issues/26)
  - [ ] [[daisy/pipeline-webui#21] Web UI job view: show details by default](https://github.com/daisy/pipeline-webui/issues/21)
  - [ ] [[daisy/pipeline-webui#29] Web UI jobs list: show which script was used for each job](https://github.com/daisy/pipeline-webui/issues/29)
  - [ ] [[daisy/pipeline-webui#30] Web UI job view: include script descriptiong in job details](https://github.com/daisy/pipeline-webui/issues/)
- [ ] [[daisy/pipeline-mod-braille#38] Fix XSLT warnings that looks like errors](https://github.com/daisy/pipeline-mod-braille/issues/38)
### Test results
- [x] All submitted ([ALL AGENCIES](https://github.com/snaekobbi/testing/blob/master/Test%20protocol/Sprint_3/All%20Agencies/System%20Test%20protocol_Braille%20DP2_Sprint%203_ALL%20AGENCIES.xlsx?raw=true))
  - [x] DE
  - [x] DK
  - [x] FI (partly)
  - [x] NL
  - [x] NO
  - [x] SE
### General issues
- [ ] [[daisy/pipeline-mod-braille#50] First CSS rule ignored if BOM (byte order mark) present](https://github.com/daisy/pipeline-mod-braille/issues/50) (reported by @mixa72)
- [ ] [[daisy/pipeline-mod-braille#52] PEF preview not rendering row spacing correctly](https://github.com/daisy/pipeline-mod-braille/issues/52)
