### ISSUE TITLE
[4.4:74] The system shall support single and double line spacing.

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#114]
### Requirement

[[4.4:74]](http://snaekobbi.github.io/requirements#4.4:74) The system shall support single and double line spacing.
### Tasks
- [x] finalise requirement: [[requirements#25] Tests for line spacing](https://github.com/snaekobbi/requirements/pull/25) (@bertfrees)
- [x] implementation: [[pipeline-mod-braille#26] Support line spacing](https://github.com/snaekobbi/pipeline-mod-braille/issues/26) (@jukkae, @bertfrees)
- [x] provide test data
  - [x] @stesk 
  - [x] @paivis 
  - [x] @dkager
- [ ] execute system tests
  - [x] @stesk ![PASS](http://snaekobbi.github.io/sprints/PASS.svg)
  - [ ] @paivis ![Ready for test](http://snaekobbi.github.io/sprints/Ready_for_test.svg)
  - [x] @dkager ![PASS](http://snaekobbi.github.io/sprints/PASS.svg)
  - [x] @mixa72 ![FAIL](http://snaekobbi.github.io/sprints/FAIL.svg)
  - [x] @JC-MTM ![FAIL](http://snaekobbi.github.io/sprints/FAIL.svg)
### Test results
- SE
  - MTM script: The test is passed when comes to double line spacing. No options available yet for single line spacing. It is probable though that the script should have generated single line spacing. 
#### Issues
- [x] [[daisy/pipeline-mod-braille#] text-align does not work in combination with line-height](https://github.com/daisy/pipeline-mod-braille/issues/54)
