### ISSUE TITLE
Deploy v1.2.0

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#115]
- [x] ~~[braille-css] Release version 1.3.0~~
- [x] [[daisy/pipeline-mod-braille#48] Release version 1.9.4](https://github.com/daisy/pipeline-mod-braille/issues/48)
- [x] [[daisy/pipeline-assembly#83] Release version 1.9.4](https://github.com/daisy/pipeline-assembly/pull/83)
- [x] [[pipeline-mod-sbs#3] Release version 1.1.0](https://github.com/snaekobbi/pipeline-mod-sbs/pull/3)
- [x] [[pipeline-mod-nlb#14] Release version 1.2.0](https://github.com/snaekobbi/pipeline-mod-nlb/pull/14)
- [x] [[system#8] Release version 1.2.0](https://github.com/snaekobbi/system/pull/8)
- [x] Install on test server
