### ISSUE TITLE
[4.4:55] The user shall be able to override the default handling of whitespace for certain elements…

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#117]
### Requirement

[[4.4:55]](http://snaekobbi.github.io/requirements#4.4:55) The user shall be able to override the default handling of whitespace for certain elements:
- Prevent collapsing of sequences of whitespace.
- Preserve leading and trailing whitespace inside block elements.
- Preserve newline characters as forced line breaks.
### Tasks
- [x] provide used CSS file (@mixa72)
- [x] fix possible issues
  - [ ] [[sbsdev/sbs-braille-tables#1] Make tables more "white space aware"](https://github.com/sbsdev/sbs-braille-tables/issues/1) (@egli, @bertfrees)
- [ ] execute system tests
  - [ ] @mixa72
  - [x] @KariRudjord ![PASS](http://snaekobbi.github.io/sprints/PASS.svg)
  - [x] @stesk ![PASS](http://snaekobbi.github.io/sprints/PASS.svg)
  - [ ] maybe @dkager? ![Ready for test](http://snaekobbi.github.io/sprints/Ready_for_test.svg)

**Comment by bertfrees** [comment]
The reason why the spaces aren't preserved in Mischa's test is because the SBS liblouis currently tables aren't compatible with my mechanism for preserving white space.

**Comment by egli** [comment]
Hm, I need more info to understand what the problem is

**Comment by egli** [comment]
The tables should be more "white space aware" now (at least in the pipeline2 branch)

**Comment by dkager** [comment]
While producing test material for our current system the following potentially useful XML fragment came up:

```
<p><code>
bel    del    hel    tel
bal    dal    hal    tal
bol    dol    hol    tol
bil    dil    hil    til
</code></p>
```

This looks like it fits 4.4:55:
- Whitespace (including newlines) between `<code>` and the first inner text should be removed.
- Whitespace (including newlines) between the last inner text and `</code>` should be removed.
- Newlines should be preserved except for the cases above.
- Whitespace should not be collapsed.

This is the first example we came up with. In particular, the use of `<code>` is an arbitrary choice. This could also be the semantically more correct `<pre>` or just `<p class="preformatted">`.

@bertfrees I sent the PEF output in an e-mail last week. If you feel this fits 4.4:55 I'd be happy to test it.

**Comment by dkager** [comment]
After looking at the [guidelines](http://www.daisy.org/z3986/structure/SG-DAISY3/part2-block.html#code): let's not put tabels in `<code>`. That having been said, I can provide some actual code with the same requirements as above.

An interesting problem is that literary braille tables are not one-to-one mappings from print to braille. Thus some source code that is spaced to look good in print may well come out very differently in braille. But I think that can't be helped. For now `<code>` is the only use case I have found for requirement 4.4:55.

**Comment by bertfrees** [comment]
> - Whitespace (including newlines) between `<code>` and the first inner text should be removed.
> - Whitespace (including newlines) between the last inner text and `</code>` should be removed.
> - Newlines should be preserved except for the cases above.
> - Whitespace should not be collapsed.

I'm not sure how we should do this. There's nothing in plain CSS for this. To be honest I think the markup is not so great. You wouldn't do it like this in EPUB3 for example. I understand why it is done this way though, probably to make it visually easier to align the columns.

Are these code blocks made especially for preformatted braille? If so, the text should also be pretranslated, otherwise the translation will mess up the formatting, as you've indicated already.

Putting tables in code is indeed bad practice in the general case, however in braille it may be unavoidable because of the weird transformations that have to be done in order to make tables understandable. So I definitely think we need to have support for preformatted braille, but 1. the text should be braille (Unicode or ASCII) and 2. I'm not sure the leading and trailing white space should be allowed.

**Comment by dkager** [comment]
The removal of leading and trailing whitespace in a block element isn't a big problem. However, I do think the `xml:space="preserve"` attribute should work, even with untranslated text. I don't think we currently do any pre-translation.

One liblouis-specific issue is that tabs aren't handled the same as they are in print. Maybe tabs should be normalized to a sequence of spaces? This will still break because of the lack of a one-to-one mapping, but at least it preserves the original layout.

**Comment by bertfrees** [comment]
The CSS property "white-space" works, even with untranslated text, except that in braille CSS it is slightly differently defined, for example that tabs are treated as single spaces. The reason for treating tabs as spaces is because it was unclear what should happen otherwise. It could be like in browsers or like in MS Word, where tabs can be used to create tables like in your example, but then there's the question of whether it's not better to use actual tables.

The "xml:space" attribute doesn't work at the moment because
1. it doesn't work in browsers, and
2. it can conflict with CSS.

I suggest that if needed we make the xml:space attribute work with a default CSS rule like

``` css
*[xml|space=preserve] {
  white-space: pre-wrap;
}
```

**Comment by dkager** [comment]
Yes, I was thinking of handling `xml:space` with CSS too. Should we have a dedicated issue for the default handling in mod-braille?

I would personally interpret the tab as either 2 or 4 spaces (probably 2 since otherwise you quickly run into the physical page limit). A similar problem exists in the US 8-dot computer braille table in liblouis that doesn't distinguish between space and tab. This has bitten me before when reading computer code using a screen reader. But whether this is truly useful probably depends on the source material too. Maybe a tab-width property/attribute somewhere?

**Comment by bertfrees** [comment]
See https://github.com/daisy/pipeline-mod-braille/issues/53.

CSS has "tab-size".

Simply replacing tabs with a number of spaces, as you propose, would be useful e.g. for source code where lines can start with tabs for indentation, but it wouldn't be as useful when tabs are used for creating tables like in your example above.

**Comment by dkager** [comment]
Note that my example was but a trial to see if it would work and be useful. It turns out it doesn't work with our current conversion so isn't used. The proper way would be to define a `<table>` with custom handling, e.g. left/center/right aligned with a minimum of N spaces between the columns.

The `tab-size` property probably provides enough flexibility for source code and other indented material.
