### ISSUE TITLE
[4.4:52] Besides left-aligned text, the system shall have support for centered and right-aligned text.

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#119]
### Requirement

[[4.4:52]](http://snaekobbi.github.io/requirements#4.4:52) Besides left-aligned text, the system shall have support for centered and right-aligned text.
### Tasks
- [x] provide used CSS files
  - [x] @mixa72
  - [x] @JC-MTM
- [x] fix issues
  - [x] [[daisy/pipeline-mod-braille#40] Default style sheets should be more basic](https://github.com/daisy/pipeline-mod-braille/issues/40) (@bertfrees)
- [x] execute system tests
  - [x] @mixa72 ![PASS](http://snaekobbi.github.io/sprints/PASS.svg)
  - [x] @JC-MTM ![PASS](http://snaekobbi.github.io/sprints/PASS.svg) / ![PASS](http://snaekobbi.github.io/sprints/PASS.svg)

**Comment by bertfrees** [comment]
The reason that left-aligned text was not completely left (wrong indent of 2 cells) in Mischa's test is because of issue https://github.com/daisy/pipeline-mod-braille/issues/40. The default values always apply unless you override them. Currently, for DTBook, all paragraph have `text-indent:2` unless you specify a different value. So in your test, if you wanted paragraphs with class `left` to have zero text-indent, you had to make that explicit:

``` css
.left {
    display: block;
    text-align: left;
    text-indent: 0;
}
```

However, as I've said in issue https://github.com/daisy/pipeline-mod-braille/issues/40, I will change the default value to `0` instead.
