### ISSUE TITLE
[4.4:47] The system shall have support for top, right, bottom and left borders and padding on blocks.

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#120]
### Requirement

[[4.4:47]](http://snaekobbi.github.io/requirements#4.4:47) The system shall have support for top, right, bottom and left borders and padding on blocks.
### Tasks
- [x] provide used CSS files
  - [x] @mixa72
  - [x] @JC-MTM 
- [ ] fix issues
  - [ ] [[daisy/pipeline-mod-braille#41] Give warning messages for CSS properties/values that are not supported by the implementation](https://github.com/daisy/pipeline-mod-braille/issues/41) (@bertfrees)
  - [x] [[daisy/pipeline-mod-braille#45] Support dot pattern '⠒' in Dotify based formatter](https://github.com/daisy/pipeline-mod-braille/issues/45) (@joeha480, @bertfrees)
  - [x] [[daisy/pipeline-mod-braille#42] margin-right and padding-right broken](https://github.com/daisy/pipeline-mod-braille/issues/42) (@bertfrees)
- [x] CSS specification: add examples of how to use the border property (@bertfrees)
- [x] execute system tests
  - [x] @mixa72 ![PASS](http://snaekobbi.github.io/sprints/PASS.svg)
  - [x] @JC-MTM ![PASS](http://snaekobbi.github.io/sprints/PASS.svg) / ![FAIL](http://snaekobbi.github.io/sprints/FAIL.svg)
### Test results
- SE
  - Main script: Extra preceeding empty line for all paragraphs: white space issue: see [[4.4:54]](https://github.com/snaekobbi/sprints/issues/125)
  - MTM script: Note that this has generated double line spacing. Borders look O.K., except for an extra line (dots1 and 3) after H1/part-heading.

**Comment by bertfrees** [comment]
There were two problems with Jens' CSS file:

``` css
level1.part h1 {
    border-top: '⠒';
    border-bottom: '⠒';
}
```
1. The patterns should be given without quotes: like `border-top: ⠒` (see http://snaekobbi.github.io/braille-css-spec/#the-border-properties)
2. Some patterns such as `⠒` (dots 25) are not supported by the Dotify-based formatter (this is a shortcoming of the software).

Qustion from Jens & Björn: we are confused. This pattern `⠒` usually works with Dotify. How come it does not work here?

The following CSS snippet works:

``` css
level1.part h1 {
    border-top: ⠉;
    border-bottom: ⠤;
}
```

**Comment by bertfrees** [comment]
Mischa's CSS file has the same problem (2nd part): pattern `⠒` is currently not supported:

``` css
.block2 {
    border-top: ⠒;
    border-bottom: ⠒;
}
```

**Comment by bertfrees** [comment]
Jens you said in your report:

> Padding: preceeding empty line before parapraphs that should have only indentation. 

What exactly did you mean by this? There is a problem regarding default CSS values, but I'm not sure this was your problem.

The issue is the following (see also issue https://github.com/daisy/pipeline-mod-braille/issues/40): The default values always apply unless you override them. This can cause confusion. Currently, for DTBook, this means that all paragraph have `text-indent:2` unless you specify a different value. So in your test, paragraphs with class `precedingemptyline` will get a preceding empty line _AND_ an indentation of 2:

``` css
p.precedingemptyline {
    padding-top: 1;
}
```

**Comment by bertfrees** [comment]
Mischa's test indeed shows that there is a problem with the `padding-right` and `margin-right` properties. Will investigate.

**Comment by dkager** [comment]
Just used this feature for the first time today. Great stuff! I'm curious if any organizations have use cases for more advanced features:
- 8-dot borders (assuming the printer can do it).
- Dashed borders.
- Multi-cell border patterns.

Dedicon currently doesn't use borders at all but I think they can be a very nice tactile aid. Just curious how hard it would be to add some of the things listed above, and if others already have experience with this subject.

**Comment by bertfrees** [comment]
Regarding use cases, let's ask the @snaekobbi/experts.

Regarding support in CSS, that should be pretty straightforward. Although I'm not sure what you mean exactly by "multi-cell border patterns".

OBFL/Dotify-wise I remember the implementation as being pretty flexible/extendable. @joeha480 any thoughts?

**Comment by dkager** [comment]
Example of a Multi-cell border pattern (two cells in this case, distinct patterns for top/right/bottom/left):

```
⠔⠢⠔⠢⠔⠢
⠪⠀⠀⠀⠀⠕
⠕⠀⠀⠀⠀⠪
⠪⠀⠀⠀⠀⠕
⠕⠀⠀⠀⠀⠪
⠊⠑⠊⠑⠊⠑
```
