### ISSUE TITLE
[4.4:46] The system shall have support for top, right, bottom and left margins on blocks.

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#121]
### Requirement

[[4.4:46]](http://snaekobbi.github.io/requirements#4.4:46) The system shall have support for top, right, bottom and left margins on blocks.
### Tasks
- [x] provide used CSS file (@JC-MTM)
- [x] fix possible issues
- [x] execute system tests (@JC-MTM) ![PASS](http://snaekobbi.github.io/sprints/PASS.svg) / ![FAIL](http://snaekobbi.github.io/sprints/FAIL.svg)
### Test results
- SE
  - Main script: Extra preceeding empty line for all paragraphs: white space issue: see [[4.4:54]](https://github.com/snaekobbi/sprints/issues/125)
  - MTM script: Note that this has generated double line spacing. Prodnote markup: questionable how this looks with single line spacing, here no extra space before and after the block as it should be.

**Comment by bertfrees** [comment]
There were two problems with Jens' CSS file:
```css
level1.part h1 {
    border-top: '⠒';
    border-bottom: '⠒';
}
```

1. The patterns should be given without quotes: like `border-top: ⠒`
2. Some patterns such as `⠒` are not supported by the Dotify-based formatter.

The following CSS snippet works:
```css
level1.part h1 {
	border-top: ⠉;
	border-bottom: ⠤;
}
```

**Comment by bertfrees** [comment]
One possible problem I can see in Jens' CSS file is the following:

``` css
book {
    margin-left: 2;
    margin-right: 2;
}
```

The `margin-left` and `margin-right` will not work unless you also specify `display: block` (see http://snaekobbi.github.io/braille-css-spec/#the-margin-properties), and currently `book` is not defined as a block element (see [default.css](https://github.com/daisy/pipeline-mod-braille/blob/49e9e0a33a1ae70a8c5271c6119ff2b315f2288e/pipeline-braille-scripts/dtbook-to-pef/src/main/resources/css/default.css)).
