### ISSUE TITLE
[4.3:41] The system shall be able to perform automatic hyphenation for uncontracted and contracted braille.

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#122]
### Requirement

[[4.3:41]](http://snaekobbi.github.io/requirements#4.3:41) The system shall be able to perform automatic hyphenation for uncontracted and contracted braille.
### Tasks
- [x] provide used CSS file (@JC-MTM)
- [x] fix possible issues
  - [ ] [[daisy/pipeline-mod-braille#44] Support hyphenation in dotify:translate](https://github.com/daisy/pipeline-mod-braille/issues/44)
  - [x] [[daisy/pipeline-mod-braille#43] Lines are broken in the middle of words when Dotify translator is used](https://github.com/daisy/pipeline-mod-braille/issues/43) (@bertfrees)
- [x] execute system tests
  - [x] @mixa72 ![PASS](http://snaekobbi.github.io/sprints/PASS.svg)
  - [X] @JC-MTM ![FAIL](http://snaekobbi.github.io/sprints/FAIL.svg) / ![PASS](http://snaekobbi.github.io/sprints/PASS.svg)
  - [x] @paivis ![PASS](http://snaekobbi.github.io/sprints/PASS.svg)
  - [x] @KariRudjord ![PASS](http://snaekobbi.github.io/sprints/PASS.svg)
### Test results
- NO: The hyphenation works, but I want it to hyphenate more. I think Bert/Ammar is working on a solution.
- SE
  - Main script: No word has been hyphenated, lines are broken between the words. 
  - MTM script: OK

**Comment by bertfrees** [comment]
In order to enable automatic hyphenation for all elements (the whole book), the following CSS snippet should be included (see also http://snaekobbi.github.io/braille-css-spec/#dfn-hyphens):

``` css
dtbook {
  hyphens: auto;
}
```

Neither the default style sheet (Mischa use no custom CSS) nor the CSS file that Jens used have this yet.

**Comment by bertfrees** [comment]
Another reason why hyphenation didn't work for Jens (that is, if he used `(translator:mtm)`), is that the MTM translator doesn't support hyphenation yet in pre-translation mode. However why words were simply cut when a row is finished is not clear to me yet. Will investigate.
