### ISSUE TITLE
[4.3:37] The system shall support the braille code used in Denmark, Norway, Sweden and Switzerland for contracted braille.

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#123]
### Requirement

[[4.3:37]](http://snaekobbi.github.io/requirements#4.3:37) The system shall support the braille code used in Denmark, Norway, Sweden and Switzerland for contracted braille.
### Tasks
- [ ] [[pipeline-mod-sbs#2] Integrate translation part of dtbook2sbsform.xsl](https://github.com/snaekobbi/pipeline-mod-sbs/issues/2) (@egli)
- [x] execute system tests
  - [x] @mixa72 ![PASS](http://snaekobbi.github.io/sprints/PASS.svg)
  - [x] @KariRudjord ![PASS](http://snaekobbi.github.io/sprints/PASS.svg)
### Test results
- NO: Grade 1 and 2 correct, just a few minor errors that Ammar will correct. My proofreader made no comments on hyphenation in contracted braille.
