### ISSUE TITLE
[4.3:34] The system shall support the braille code used in Denmark, Finland, Norway, Sweden, Switzerland and the Netherlands for uncontracted braille.

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#124]
### Requirements
- [[4.3:34]](http://snaekobbi.github.io/requirements#4.3:34) The system shall support the braille code used in Denmark, Finland, Norway, Sweden and Switzerland for uncontracted braille.
- [[4.3:34C]](http://snaekobbi.github.io/requirements#4.3:34C) The system shall support the braille code used in the Netherlands for uncontracted braille.
### Tasks
- [ ] [[pipeline-mod-sbs#2] Integrate translation part of dtbook2sbsform.xsl](https://github.com/snaekobbi/pipeline-mod-sbs/issues/2) (@egli)
- [ ] fix issues
  - [ ] issues in Norwegian uncontracted: [liblouis#4](https://github.com/snaekobbi/liblouis/issues/4) (@usama49, @bertfrees)
  - [x] support `(grade:0)` for German (@bertfrees)
- [ ] execute system tests
  - [x] @paivis ![PASS](http://snaekobbi.github.io/sprints/PASS.svg)
  - [ ] @mixa72
  - [x] @KariRudjord ![PASS](http://snaekobbi.github.io/sprints/PASS.svg)
  - [x] @JC-MTM ![PASS](http://snaekobbi.github.io/sprints/PASS.svg) / ![PASS](http://snaekobbi.github.io/sprints/PASS.svg)
### Test results
- FI: The characters in the Finnish Braille table are correct but we need a way to handle all other characters that might exist in the source file. We might need different handling to these characters in different books. Like à might be a or ~a or à depending on the context. In this book I wouldn't want to have ~o in Nesb&#xf8; but ö. And we want never the hexadecimal codes to be in the Braille, like &#xbb;. is in this case.
#### Issues
- [ ] [celia] Different handling of certain foreign characters in different books
- [ ] [celia] Handle characters not defined in the Finnish braille table, but never have hexadecimal codes in braille
