### ISSUE TITLE
[4.4:54] The system shall by default handle whitespace characters in the source XML according to the following rules…

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#125]
### Requirement

[[4.4:54]](http://snaekobbi.github.io/requirements#4.4:54) The system shall by default handle whitespace characters (spaces, tabs, line feeds) in the source XML according to the following rules:
- Comments are removed entirely and do not affect whitespace handling.
- All whitespace surrounding block elements is removed.
- Leading and trailing whitespace inside block elements are removed.
- Sequences of whitespace characters are reduced to a single space character. Newline characters are handled as other whitespace.
### Tasks
- [x] provide test data (@dkager) (https://github.com/snaekobbi/testing/pull/3)
- [x] execute system tests
  - [x] @dkager ![PASS](http://snaekobbi.github.io/sprints/PASS.svg)
  - [x] @KariRudjord ![PASS](http://snaekobbi.github.io/sprints/PASS.svg)
### 2nd iteration (v1.2.1)
- [x] execute system test: @JC-MTM ![FAIL](http://snaekobbi.github.io/sprints/FAIL.svg)
### Test results
- SE
  - Main script: Extra preceeding empty line for all paragraphs. Same result in 2nd iteration.
#### Issues
- [x] [[daisy/pipeline-mod-braille#49] Empty blocks or blocks with only collapsible white space should not create empty lines](https://github.com/daisy/pipeline-mod-braille/issues/49) ![priority:1](http://snaekobbi.github.io/sprints/priority_1.svg)
- [x] [daisy/pipeline-mod-braille] White space that surrounds block elements should never generate empty lines, also if it was translated to blank braille patterns (e.g. by Dotify translator) (fixed by commit https://github.com/daisy/pipeline-mod-braille/commit/906089edf517dd3953d8bf58b81a96fa4f4b8993)
