### ISSUE TITLE
Deploy v1.2.1

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#126]
- [x] [[braille-css#6] Release version 1.3.0](https://github.com/snaekobbi/braille-css/pull/6)
- [x] [joeha480/dotify] Release dotify.task.impl 1.0.0 (@joeha480)
- [x] [joeha480/dotify] Release dotify.formatter.impl 1.1.3 (@joeha480)
- [x] [[daisy/pipeline-build-utils#23] Release modules-parent 1.3](https://github.com/daisy/pipeline-build-utils/pull/23) (@bertfrees, @rdeltour)
- [x] [[daisy/pipeline-mod-braille#51] Release version 1.9.5](https://github.com/daisy/pipeline-mod-braille/pull/51)
- [x] [[daisy/pipeline-assembly#48] Release version 1.9.5](https://github.com/daisy/pipeline-assembly/pull/84)
- [x] ~~[sbsdev/sbs-braille-tables] Release new version~~ (@egli)
- [x] [[pipeline-mod-mtm#3] Release version 1.1.0](https://github.com/snaekobbi/pipeline-mod-mtm/pull/3)
- [x] ~~[pipeline-mod-sbs] Release version 1.1.1~~
- [x] ~~[pipeline-mod-dedicon] Release version 1.1.0~~
- [x] [system] Release version 1.2.1: https://github.com/snaekobbi/system/releases/tag/v1.2.1
- [ ] Install on test server
