### ISSUE TITLE
sprint#4

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#127]
[Deployment of 1.3.0](https://github.com/snaekobbi/sprints/issues/134) is planned for Wednesday 14 October. A second iteration will follow the week after.
### Tasks

![priority:1](http://snaekobbi.github.io/sprints/priority_1.svg)
- [ ] Re-execute some tests from sprint#3 after resolving issues (@snaekobbi/testers, see [sub-issues](https://github.com/snaekobbi/sprints/milestones/sprint%234))
- [x] Implement pagination related features (@jukkae, @joeha480, @bertfrees, see [sub-issues](https://github.com/snaekobbi/sprints/milestones/sprint%234))
- [x] Test pagination related features. Some other features such as (page) numbering will be tested implicitly. The proposal is that each agency performs a number of tests (can be one, two or more files) that together cover all the pagination features that they need. (@snaekobbi/testers)
- [x] Continue work on documentation (@bertfrees)
- [ ] Solve performance issues
- [ ] Continuous improvement to translation/hyphenation (see [sub-issues](https://github.com/snaekobbi/sprints/milestones/sprint%234))
  - [ ] German translation (@egli, @bertfrees)
  - [x] Norwegian translation and hyphenation (@usama49, @bertfrees)
  - [ ] Finnish translation (@jukkae)
- [x] Finish work on re-running jobs, continue work on templates (@josteinaj)

![priority:2](http://snaekobbi.github.io/sprints/priority_2.svg)
- [ ] Improve MTM script
  - [ ] [[pipeline-mod-mtm#9] Validate DTBook before converting](https://github.com/snaekobbi/pipeline-mod-mtm/issues/9)
  - [ ] [[pipeline-mod-mtm#10] Validate PEF result](https://github.com/snaekobbi/pipeline-mod-mtm/issues/10)
  - [ ] [[pipeline-mod-mtm#4] Datatypes in Web GUI](https://github.com/snaekobbi/pipeline-mod-mtm/issues/4) (depends on fwk)
  - [ ] [[pipeline-mod-mtm#7] Set the folder name in the result zip](https://github.com/snaekobbi/pipeline-mod-mtm/issues/7) (depends on fwk)
- [x] Prepare requirements for sprint#5 (@snaekobbi/experts)
### Issues
- [x] On elements with a left/right border the left/right margin is not placed correctly (regression reported by @mixa72) (fixed by https://github.com/daisy/pipeline-mod-braille/commit/7609e2648dea91936988354f99d2e413436448eb)
### Test results
- [Protocol all agencies](https://github.com/snaekobbi/testing/raw/master/Test%20protocol/Sprint_4/All%20Agencies/System%20Test%20protocol_Braille%20DP2_Sprint%204_ALL%20AGENCIES_.xlsx)
- [Report by Denis](https://github.com/snaekobbi/testing/blob/master/Test%20reports/Test%20report_Braille%20DP2%20v1.1%20Sprint_4.docx)
