### ISSUE TITLE
[4.3:34] The system shall support the braille code used in Denmark, Finland, Norway, Sweden, Switzerland and the Netherlands for uncontracted braille.

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#128]
### Requirements
- [[4.3:34]](http://snaekobbi.github.io/requirements#4.3:34) The system shall support the braille code used in Denmark, Finland, Norway, Sweden and Switzerland for uncontracted braille.
- [[4.3:34C]](http://snaekobbi.github.io/requirements#4.3:34C) The system shall support the braille code used in the Netherlands for uncontracted braille.
### Tasks
- [ ] German (@egli)
  - [ ] [[pipeline-mod-sbs#2] Integrate translation part of dtbook2sbsform.xsl](https://github.com/snaekobbi/pipeline-mod-sbs/issues/2)
- [ ] Norwegian (@usama49)
  - [ ] Various [issues](https://github.com/snaekobbi/pipeline-mod-nlb/issues) (to be decided which)
- [ ] Finnish (@jukkae)
  - [ ] Different handling of certain foreign characters in different books
  - [x] Handle characters not defined in the Finnish braille table, but never have hexadecimal codes in braille
- [x] Dutch (@dkager)
  - [x] [[pipeline-mod-dedicon#3] Show a special dot pattern for unknown characters](https://github.com/snaekobbi/pipeline-mod-dedicon/issues/3)
- [ ] execute system tests
  - [ ] @paivis
  - [ ] @mixa72
  - [ ] @KariRudjord ![Ready for test](http://snaekobbi.github.io/sprints/Ready_for_test.svg)
  - [ ] @dkager ![Ready for test](http://snaekobbi.github.io/sprints/Ready_for_test.svg)

**Comment by jukkae** [comment]
Handled undefined characters in a similar way as @dkager in https://github.com/snaekobbi/pipeline-mod-dedicon/issues/3 for now - I guess we'd still like to have a warning on UI.
