### ISSUE TITLE
[4.3:37] The system shall support the braille code used in Denmark, Norway, Sweden and Switzerland for contracted braille.

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#130]
### Requirement

[[4.3:37]](http://snaekobbi.github.io/requirements#4.3:37) The system shall support the braille code used in Denmark, Norway, Sweden and Switzerland for contracted braille.
### Tasks
- [ ] German (@egli)
  - [ ] [[pipeline-mod-sbs#2] Integrate translation part of dtbook2sbsform.xsl](https://github.com/snaekobbi/pipeline-mod-sbs/issues/2)
- [ ] Norwegian (@usama49)
  - [ ] Various [issues](https://github.com/snaekobbi/pipeline-mod-nlb/issues) (to be decided which exactly)
- [ ] execute system tests
  - [ ] @mixa72
  - [ ] @KariRudjord
