### ISSUE TITLE
[4.3:41] The system shall be able to perform automatic hyphenation for uncontracted and contracted braille.

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#131]
### Requirement

[[4.3:41]](http://snaekobbi.github.io/requirements#4.3:41) The system shall be able to perform automatic hyphenation for uncontracted and contracted braille.
### Tasks
- [ ] New workflow for Norwegian hyphenation (@usama49)
- [ ] [[daisy/pipeline-mod-braille#44] Support hyphenation in dotify:translate](https://github.com/daisy/pipeline-mod-braille/issues/44) (@bertfrees)
- [ ] execute system test: @JC-MTM (main script)
