### ISSUE TITLE
[4.4:55] The user shall be able to override the default handling of whitespace for certain elements…

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#132]
### Requirement

[[4.4:55]](http://snaekobbi.github.io/requirements#4.4:55) The user shall be able to override the default handling of whitespace for certain elements:
- Prevent collapsing of sequences of whitespace.
- Preserve leading and trailing whitespace inside block elements.
- Preserve newline characters as forced line breaks.
### Tasks
- [ ] [[sbsdev/sbs-braille-tables#1] Make tables more "white space aware"](https://github.com/sbsdev/sbs-braille-tables/issues/1) (@egli)
- [x] [pipeline-mod-dedicon] Handle xml:space="preserve"
- [ ] execute system tests
  - [ ] @mixa72
  - [ ] @dkager ![Ready for test](http://snaekobbi.github.io/sprints/Ready_for_test.svg)
