### ISSUE TITLE
[4.4:74] The system shall support single and double line spacing.

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#133]
### Requirement

[[4.4:74]](http://snaekobbi.github.io/requirements#4.4:74) The system shall support single and double line spacing.
### Tasks
- [x] execute system tests (v1.2.2)
  - [x] Test that https://github.com/daisy/pipeline-mod-braille/issues/54 is fixed (@mixa72) ![PASS](http://snaekobbi.github.io/sprints/PASS.svg)
  - [x] @JC-MTM (MTM-script) ![PASS](http://snaekobbi.github.io/sprints/PASS.svg)
  - [x] @paivis ![PASS](http://snaekobbi.github.io/sprints/PASS.svg)
- [x] regression test
  - [x] @KariRudjord ![PASS](http://snaekobbi.github.io/sprints/PASS.svg)
