### ISSUE TITLE
Deploy v1.3.0

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#134]
- [x] [[braille-css#9] Release version 1.4.0](https://github.com/snaekobbi/braille-css/pull/9)
- [x] [[daisy/pipeline-mod-braille#57] Release version 1.9.6](https://github.com/daisy/pipeline-mod-braille/pull/57)
- [x] [[daisy/pipeline-assembly#89] Release version 1.9.6](https://github.com/daisy/pipeline-assembly/pull/89)
- [x] [[pipeline-mod-sbs#4] Release version 1.1.1](https://github.com/snaekobbi/pipeline-mod-sbs/pull/4)
- [x] [[pipeline-mod-nota#2] Release version 1.0.1](https://github.com/snaekobbi/pipeline-mod-nota/pull/2)
- [x] [[pipeline-mod-nlb#16] Release version 1.3.0](https://github.com/snaekobbi/pipeline-mod-nlb/pull/16)
- [x] [[pipeline-mod-mtm#11] Release version 1.3.0](https://github.com/snaekobbi/pipeline-mod-mtm/pull/11)
- [x] [[pipeline-mod-dedicon#4] Release version 1.1.0](https://github.com/snaekobbi/pipeline-mod-dedicon/pull/4)
- [x] [[pipeline-mod-celia#2] Release version 1.0.1](https://github.com/snaekobbi/pipeline-mod-celia/pull/2)
- [x] [system] Release version 1.3.0
