### ISSUE TITLE
[4.4:75] When printing double-sided with line spacing greater than 1, printed lines shall alternate on odd and even pages.

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#135]
### Requirement

[[4.4:75]](http://snaekobbi.github.io/requirements#4.4:75) When printing double-sided with line spacing greater than 1, printed lines shall alternate on odd and even pages.
### Tasks
- [x] execute system test (v1.2.2)
  - [x] @paivis ![PASS](http://snaekobbi.github.io/sprints/PASS.svg)
- [x] regression test (v1.3.0)
  - [x] @mixa72 ![PASS](http://snaekobbi.github.io/sprints/PASS.svg)
  - [x] @JC-MTM (MTM-script) ![PASS](http://snaekobbi.github.io/sprints/PASS.svg)
  - [x] @KariRudjord ![PASS](http://snaekobbi.github.io/sprints/PASS.svg)
