### ISSUE TITLE
[4.5:78] The user shall have control over page breaking…

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#137]
### Requirement

[[4.5:78]](http://snaekobbi.github.io/requirements#4.5:78) The user shall have control over page breaking by means of
- inserting hard page breaks,
- protecting blocks from being split across multiple pages,
- avoiding page breaks within blocks leaving only the first line(s) on the first page (orphan control),
- avoiding page breaks within blocks leaving only the last line(s) on the second page (widow control), and
- keeping a block’s first line(s) on the same page as the preceding block.
### Tasks
- [x] implementation
  - [x] Fix keep and keep-with-next in Dotify (https://github.com/joeha480/dotify/issues/101) (@joeha480)
  - [x] Add support for widows and orphans in Dotify (@joeha480)
  - [x] Implement and test in css-to-obfl (~~@jukkae~~ @bertfrees): see https://github.com/daisy/pipeline-mod-braille/commit/2e328f8f6fd74a5e0d932d47db235dd943455bb7
- [x] examples or orphans/widows in braille CSS specification (@bertfrees): see http://snaekobbi.github.io/braille-css-spec/#controlling-page-breaks
- [x] system tests
  - [x] @mixa72 ![FAIL](http://snaekobbi.github.io/sprints/FAIL.svg)
  - [x] @stesk ![PASS](http://snaekobbi.github.io/sprints/PASS.svg)
  - [x] @KariRudjord ![PASS](http://snaekobbi.github.io/sprints/PASS.svg)
### Issues
- [ ] some remaining Dotify bugs w.r.t. pagination (test by @mixa72): see https://github.com/daisy/pipeline-mod-braille/commit/9b83c2cb959b2b62e8670f9543b57d66ebe7ac6f and https://github.com/joeha480/dotify/pull/142
