### ISSUE TITLE
[4.7:102] The system shall be able to evaluate certain variables and counters at so-called fields…

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#138]
### Requirement

[[4.7:102]](http://snaekobbi.github.io/requirements#4.7:102) The system shall be able to evaluate certain variables and counters at so-called "fields", for example on the title page or in the page header or footer. Supported variables shall include at least the current braille page number, the current print page number or range of print pages contained in the current braille page, the current volume number, the total number of volumes, the total number of braille pages or sheets contained in the current volume or book, the current chapter title, the current chapter number, and the date.
## [:rewind:](https://github.com/snaekobbi/sprints/issues/82) sprint#5 [:fast_forward:](https://github.com/snaekobbi/sprints/issues/141)

In this sprint we deal with only braille page numbering and print page numbering (including page range) in the header/footer in various required number formats.
### Tasks
- [x] specification
  - [x] [[braille-css-spec#17] Named strings](https://github.com/snaekobbi/braille-css-spec/issues/17): optional second argument to `string()` (@bertfrees): see http://snaekobbi.github.io/braille-css-spec/#h3_named-strings
- [x] implementation
  - [x] Test Joel's recent OBFL/Dotify additions to support print page ranges (incl./especially edge cases) (@bertfrees, @jukkae)
  - [x] [[pipeline-mod-braille#23] Support print pages](https://github.com/snaekobbi/pipeline-mod-braille/issues/23): support print page ranges in css-to-obfl (~~@jukkae~~ @bertfrees)
- [x] examples in braille CSS specification (@bertfrees)
  - [x] `string()` function: see http://snaekobbi.github.io/braille-css-spec/#the-string-function
  - [x] print page ranges: see http://snaekobbi.github.io/braille-css-spec/#original-pagination
  - [x] ~~number formats~~
- [x] system tests
  - [x] @mixa72 ![FAIL](http://snaekobbi.github.io/sprints/FAIL.svg) (known issues)
  - [x] @stesk ![FAIL](http://snaekobbi.github.io/sprints/FAIL.svg) (known issues)
### Known issues
- If the print page range is covering the page spread (left+right pages) it is possibly wrong on the first page (i.e. where there is no left page). One solution could be to support a `@page:first` rule which would have a more limited scope. The other solution is to change the definitions of `spread-start` etc.
- If print page breaks within paragraphs are not rendered in the text (only in header/footer) the resulting header/footer is as if the breaks they were moved to the start of the following paragraph. This can be fixed by enclosing the `pagenum`s in `<p></p>` tags, however this will also result in forced line breaks.
### Other issues
- [ ] `page-start` does not behave correct if no assignment has been made yet at the start of page which has an assignment in it (reported by @dkager)

**Comment by dkager** [comment]
In the spirit of requirements clarification/justification:
Dedicon has a use case for the date field. We currently use e.g. 'november 2015', but a close approximation would be good enough.

**Comment by bertfrees** [comment]
Regarding the first known issue: I have decided to support `@page:first` anyway because it may have other use cases (https://github.com/snaekobbi/braille-css-spec/commit/e6311c8684913614b44df4cdc2be92189dad8742). Later we can still decide to change the definitions of `spread-foo` to match the expected behavior.

**Comment by dkager** [comment]
See also snaekobbi/pipeline-mod-dedicon@7b2146c for a potential issue (or goof-up on my end, who knows).
