### ISSUE TITLE
Deploy v1.4.0

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#140]
- [x] ~~[[braille-css#11] Release version 1.5.0](https://github.com/snaekobbi/braille-css/pull/11)~~
- [x] [[daisy/pipeline-mod-braille#62] Release version 1.9.7](https://github.com/daisy/pipeline-mod-braille/pull/62)
- [x] [[daisy/pipeline-assembly#90] Release version 1.9.7](https://github.com/daisy/pipeline-assembly/pull/90)
- [x] [[pipeline-mod-sbs#5] Release version 1.2.0](https://github.com/snaekobbi/pipeline-mod-sbs/pull/5)
- [x] [system] Release version 1.4.0
