### ISSUE TITLE
[4.7:102] The system shall be able to evaluate certain variables and counters at so-called fields…

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#141]
### Requirement

[[4.7:102]](http://snaekobbi.github.io/requirements#4.7:102) The system shall be able to evaluate certain variables and counters at so-called "fields", for example on the title page or in the page header or footer. Supported variables shall include at least the current braille page number, the current print page number or range of print pages contained in the current braille page, the current volume number, the total number of volumes, the total number of braille pages or sheets contained in the current volume or book, the current chapter title, the current chapter number, and the date.
### Tasks
- [ ] Fix issues in implementation
  - [x] [[joeha480/dotify#143] Behavior of scope=spread on first page of sequence](https://github.com/joeha480/dotify/issues/143)
  - [ ] [[joeha480/dotify#144] Behavior of scope=page-content/start-offset=-1 on first page of volume/document](https://github.com/joeha480/dotify/issues/144)
  - [ ] [[daisy/pipeline-mod-braille#64] Fix page-start and spread-start](https://github.com/daisy/pipeline-mod-braille/issues/64) (@bertfrees)
  - [x] [[daisy/pipeline-mod-braille#65] Fix behavior of string-set on inline elements](https://github.com/daisy/pipeline-mod-braille/issues/65) (@bertfrees)
- [ ] repeat system tests
  - [ ] @dkager 
  - [ ] @mixa72 
  - [ ] @stesk
