### ISSUE TITLE
[4.7:102] The system shall be able to evaluate certain variables and counters at so-called fields…

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#148]
### Requirement

[[4.7:102]](http://snaekobbi.github.io/requirements#4.7:102) The system shall be able to evaluate certain variables and counters at so-called "fields", for example on the title page or in the page header or footer. Supported variables shall include at least the current braille page number, the current print page number or range of print pages contained in the current braille page, the current volume number, the total number of volumes, the total number of braille pages or sheets contained in the current volume or book, the current chapter title, the current chapter number, and the date.
### Tasks
- [ ] fix issues (@bertfrees)
  - [ ] [[daisy/pipeline-mod-braille#64] Fix page-start and spread-start](https://github.com/daisy/pipeline-mod-braille/issues/64)
  - [ ] [[joeha480/dotify#144] Behavior of scope=page-content/start-offset=-1 on first page of volume/document](https://github.com/joeha480/dotify/issues/144)

These issues have not been fixed but instead I added support for `page-start-except-last` and `spread-start-except-last` which works better.
