### ISSUE TITLE
[4.3:36] The system shall support double letter spacing…

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#15]
### Requirement

[[4.3:36]](http://snaekobbi.github.io/requirements#4.3:36) The system shall support double letter spacing, meaning adding a space between characters. Some characters should be kept together such as a capital sign and a letter.
### Tasks
- [x] finalize requirements (@bertfrees): https://github.com/snaekobbi/requirements/pull/2
- [ ] braille CSS specification (@jukkae, @bertfrees): https://github.com/snaekobbi/braille-css-spec/issues/15
- [ ] implementation (@jukkae): https://github.com/snaekobbi/pipeline-mod-braille/issues/24
