### ISSUE TITLE
Deploy v1.5.0

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#156]
- [x] [jStyleParser] Release version 1.20-p4
- [x] [[braille-css#13] Release version 1.6.0](https://github.com/snaekobbi/braille-css/pull/13)
- [x] [[daisy/pipeline-framework#100] Release version 1.10.0](https://github.com/daisy/pipeline-framework/pull/100)
  - includes:
    - https://github.com/daisy/pipeline-framework/pull/84
    - https://github.com/daisy/pipeline-framework/pull/90
    - https://github.com/daisy/pipeline-framework/pull/95
    - https://github.com/daisy/pipeline-framework/pull/97
- [x] [[daisy/pipeline-mod-braille#66] Release version 1.9.8](https://github.com/daisy/pipeline-mod-braille/pull/66)
- [x] [[daisy/pipeline-assembly#91] Release version 1.9.8](https://github.com/daisy/pipeline-assembly/pull/91)
- [x] [[pipeline-mod-sbs#6] Release version 1.3.0](https://github.com/snaekobbi/pipeline-mod-sbs/pull/6)
- [x] [[pipeline-mod-celia#3] Release version 1.1.0](https://github.com/snaekobbi/pipeline-mod-celia/pull/3)
- [x] [[pipeline-mod-nota#3] Release version 1.1.0](https://github.com/snaekobbi/pipeline-mod-nota/pull/3)
- [x] [[pipeline-mod-nlb#19] Release version 1.4.0](https://github.com/snaekobbi/pipeline-mod-nlb/pull/19)
- [x] [[pipeline-mod-mtm#13] Release version 1.4.0](https://github.com/snaekobbi/pipeline-mod-mtm/pull/13)
- [x] [[pipeline-mod-dedicon#9] Release version 1.2.0](https://github.com/snaekobbi/pipeline-mod-dedicon/pull/9)
- [x] [system] Release version 1.5.0

**Comment by bertfrees** [comment]
- [x] To do: release all staged artifacts

**Comment by bertfrees** [comment]
Also to do: all the release notes
