### ISSUE TITLE
[4.6:91] In the case of an extended table of contents that is not trimmed down, it shall be possible to group entries according to volume…

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#157]
### Requirement

[[4.6:91]](http://snaekobbi.github.io/requirements#4.6:91) In the case of an extended table of contents that is not trimmed down (e.g. in the first volume), it shall be possible to group entries according to volume and insert a heading before each group.
### Tasks
- [x] Finish support for basic volume splitting in CSS parser and CSS-to-OBFL (@bertfrees)
- [x] system tests
  - [x] ~~@KariRudjord ![Ready for test](http://snaekobbi.github.io/sprints/Ready_for_test.svg)~~
  - [x] @stesk ![FAIL](http://snaekobbi.github.io/sprints/FAIL.svg)
### Test results
- DA: Tested CSS selector -obfl-on-volume-start, which seems not to work.
### Issues
- [x] Fix support for -obfl-on-volume-start, and also add -obfl-on-toc-start, -obfl-on-volume-end and -obfl-on-toc-end.
