### ISSUE TITLE
[4.6:90] The system shall support trimming down of a table of contents to a volume-scope table of contents…

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#158]
### Requirement

[[4.6:90]](http://snaekobbi.github.io/requirements#4.6:90) The system shall support trimming down of a table of contents to a volume-scope table of contents that includes only the entries that reference items present in the current volume.
### Tasks
- [x] Finish support for basic volume splitting in CSS parser and CSS-to-OBFL (@bertfrees)
- [x] system tests
  - [x] @KariRudjord ![PASS](http://snaekobbi.github.io/sprints/PASS.svg)
  - [x] @stesk ![PASS](http://snaekobbi.github.io/sprints/PASS.svg)
### Suggestions
- [ ] A feature request: Volume-level TOCs and the overall TOC should not have the same CSS selector. It may be desirable to have different styling depending on the TOC scope.
