### ISSUE TITLE
[4.3:37] The system shall support the braille code used in Denmark, Norway, Sweden and Switzerland for contracted braille.

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#16]
### Requirement

[[4.3:37]](http://snaekobbi.github.io/requirements#4.3:37) The system shall support the braille code used in Denmark, Norway, Sweden and Switzerland for contracted braille.
### Tasks
- [ ] update requirement (@bertfrees)
  - [ ] [[requirements#3] Tests for Danish translation](https://github.com/snaekobbi/requirements/issues/3)
  - [ ] [[requirements#5] Tests for Swedish translation](https://github.com/snaekobbi/requirements/pull/5)
  - [ ] [[requirements#6] Tests for Norwegian translation](https://github.com/snaekobbi/requirements/pull/6)
  - [ ] [[requirements#7] Tests for German (Swiss) translation](https://github.com/snaekobbi/requirements/issues/7)
  - [ ] re-evaluate priority of contracted braille for the various languages
- [x] integration (@bertfrees 4h)
  - [x] [[issues#12] Pipeline braille module per agency](https://github.com/snaekobbi/issues/issues/12)
  - [x] [[issues#14] Higher level translator components for all languages](https://github.com/snaekobbi/issues/issues/14)
  - [x] [[issues#13] Integrate latest liblouis tables](https://github.com/snaekobbi/issues/issues/13)
- [x] provide test data
  - [x] German (@mixa72 5hr)
  - [x] Danish (@stesk 4hr)
- [x] execute system tests
  - [x] German (@mixa72 5hr) ![FAIL](http://snaekobbi.github.io/sprints/FAIL.svg)
  - [ ] Danish (@stesk 4hr) ![Ready for test](http://snaekobbi.github.io/sprints/Ready_for_test.svg)
### Test results
- [System Test protocol_Braille DP2 v1.0_DE.xlsx
  ](https://github.com/snaekobbi/testing/blob/master/Test%20protocol/Sprint_1
  /DE/System%20Test%20protocol_Braille%20DP2%20v1.0_DE.xlsx?raw=true)
#### Issues
- [x] [[system#2] System should start up properly each time](https://github.com/snaekobbi/system/issues/2)
- [ ] [[daisy/pipeline-webui#26] Job page keeps showing "Running..."](https://github.com/daisy/pipeline-webui/issues/26)
