### ISSUE TITLE
[4.3:38] The system shall support marking of text-level semantics with braille indicators.

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#162]
### Requirement

[[4.3:38]](http://snaekobbi.github.io/requirements#4.3:38) The system shall support marking of text-level semantics (i.e. em, strong) with braille indicators.
### Tasks
- [ ] Implement, test and document new design for capitals and emphasis (@egli, @dkager, @bertfrees)
  - [ ] Test using the existing test data from APH (moved to YAML test framework) and new "exhaustive" test framework.
  - [ ] Implement, aided by the exhaustive tests, and hopefully by largely reusing the existing code.
  - [ ] Document, starting from the tests and documentation on the wiki
