### ISSUE TITLE
Deploy 1.6.0

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#164]
- [x] [jStyleParser] Release version 1.20-p5
- [x] [[braille-css#15] Release version 1.7.0](https://github.com/snaekobbi/braille-css/pull/15)
- [x] ~~[daisy/pipeline-framework] Release new framework-core~~
  - daisy/pipeline-framework#103
- [x] [[daisy/pipeline-mod-braille#74] Release version 1.9.9](https://github.com/daisy/pipeline-mod-braille/pull/74)
- [x] [[daisy/pipeline-assembly#96] Release version 1.9.9](https://github.com/daisy/pipeline-assembly/pull/96)
- [x] [[pipeline-mod-nlb#21] Release version 1.5.0](https://github.com/snaekobbi/pipeline-mod-nlb/pull/21)
- [x] [pipeline-mod-sbs] Release version 1.3.1
- [x] [system] Release version 1.6.0
- [x] Upgrade test-server
