### ISSUE TITLE
[4.4:57] There shall be the option to reformat a table into a list…

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#167]
### Requirement

[[4.4:57]](http://snaekobbi.github.io/requirements#4.4:57) There shall be the option to reformat a table into a list,
- either by linearizing the table row-by-row with delimiters between cells,
- or by rendering each row as a sublist, where the cells are the list items. It must be possible to set off cells with a left margin according to their column, so that a stairstep format can be accomplished.
- It must be possible to prepend cells with their column header.
### Tasks
- [x] implement some suggestions from system tests in sprint#7 (@bertfrees)
- [ ] additional system tests
  - [x] @KariRudjord ![PASS](http://snaekobbi.github.io/sprints/PASS.svg) (we could have worked more with it, but consider that we don't have experience in producing lists, we are ok for now)
  - [ ] @paivis ![Ready for test](http://snaekobbi.github.io/sprints/Ready_for_test.svg)
  - [ ] @BWestling (MTM script)
  - [ ] @JC-MTM (MTM script)
### Test results
- DK: As Bert and I have discussed on IRC, there is a need for a CSS parameter/value which alters the algorithm used to locate header cells such that it looks up before looking left (in order to get proper render-by-column table layouts).

**Comment by bertfrees** [comment]
@stesk Regarding your comment above: that issue should have been resolved already, so I assume you haven't retested?

**Comment by stesk** [comment]
@bertfrees You're right, I haven't retested. I will do that as soon as possible.
