### ISSUE TITLE
[4.4:58] There shall be the option to render a table in matrix format…

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#168]
### Requirement

[[4.4:58]](http://snaekobbi.github.io/requirements#4.4:58) There shall be the option to render a table in matrix format, thereby mimicking the original form. This feature shall be supported at least for small tables that fit on a page horizontally without the need for text wrapping in cells, and that have no column- or rowspan. The matrix format supports borders and padding on rows, columns and cells.
### Tasks
- [ ] system tests
  - [ ] @dkager ![Ready for test](http://snaekobbi.github.io/sprints/Ready_for_test.svg)
  - [x] @stesk ![PASS](http://snaekobbi.github.io/sprints/PASS.svg)
  - [x] @mixa72 ![PASS](http://snaekobbi.github.io/sprints/PASS.svg)

**Comment by bertfrees** [comment]
I have given an explanation about how to use this feature in an email.
