### ISSUE TITLE
[3.4:8] The system shall support EPUB 3 as input.

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#171]
### Requirement

[3.4:8] The system shall support EPUB 3 (conforming to the MTM procurement specification) as input.
### Tasks
- [x] epub3-to-pef script (@josteinaj)
- [x] system tests
  - [x] NLB ![PASS](http://snaekobbi.github.io/sprints/PASS.svg)
  - [x] Nota ![PASS](http://snaekobbi.github.io/sprints/PASS.svg)
### Issues
- [ ] `stylesheet` option does not support relative paths
