### ISSUE TITLE
Deploy 1.7.0

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#172]
- [x] [[braille-css#16] Release version 1.8.0](https://github.com/snaekobbi/braille-css/pull/16)
- [x] [[braille-css#18] Release version 1.9.0](https://github.com/snaekobbi/braille-css/pull/18)
- [x] [jStyleParser] Release version 1.20-p6 (staged)
- [x] [jsass] Release version 4.1.0-p1
- [x] [[daisy/pipeline-mod-braille#95] Release version 1.9.10](https://github.com/daisy/pipeline-mod-braille/pull/95)
- [x] [[daisy/pipeline-mod-braille#102] Release version 1.9.11](https://github.com/daisy/pipeline-mod-braille/pull/102)
- [x] [[daisy/pipeline-assembly#98] Release version 1.9.10](https://github.com/daisy/pipeline-assembly/pull/98)
- [ ] [[daisy/pipeline-assembly#101] Release version 1.9.11](https://github.com/daisy/pipeline-assembly/pull/101)
- [x] [[pipeline-mod-nlb#28] Release version 1.6.0](https://github.com/snaekobbi/pipeline-mod-nlb/pull/28)
- [ ] [[pipeline-mod-nlb#37] Release version 1.7.0](https://github.com/snaekobbi/pipeline-mod-nlb/pull/37)
- [ ] [[pipeline-mod-nota#10] Release version 1.2.0](https://github.com/snaekobbi/pipeline-mod-nota/pull/10)
- [ ] [[pipeline-mod-mtm#23] Release version 1.5.0](https://github.com/snaekobbi/pipeline-mod-mtm/pull/23)
- [ ] [[pipeline-mod-celia#14] Release version 1.2.0](https://github.com/snaekobbi/pipeline-mod-celia/pull/14)
- [ ] [[pipeline-mod-dedicon#34] Release version 1.4.0](https://github.com/snaekobbi/pipeline-mod-dedicon/pull/34)
- [ ] [[pipeline-mod-sbs#12] Release version 1.4.0](https://github.com/snaekobbi/pipeline-mod-sbs/pull/12)
- [ ] [[system#13] Release version 1.7.0](https://github.com/snaekobbi/system/pull/13)

**Comment by bertfrees** [comment]
Staged artifacts have been dropped. Need to re-upload.
