### ISSUE TITLE
Deploy 1.8.0

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#173]
- [x] [liblouis-java] Release version 2.0.0
- [x] [[braille-css#19] Release version 1.10.0](https://github.com/snaekobbi/braille-css/pull/19)
- [x] [jStyleParser] Release version 1.20-p7
- [x] [[daisy/pipeline-mod-braille#108] Release version 1.9.12](https://github.com/daisy/pipeline-mod-braille/pull/108)
- [x] [[daisy/pipeline-assembly#102] Release version 1.9.12](https://github.com/daisy/pipeline-assembly/pull/102)
- [x] [[pipeline-mod-nlb#40] Release version 1.8.0](https://github.com/snaekobbi/pipeline-mod-nlb/pull/40)
- [x] [[pipeline-mod-nota#17] Release version 1.3.0](https://github.com/snaekobbi/pipeline-mod-nota/pull/17)
- [x] [pipeline-mod-nota] Release version 1.3.1
- [x] [[pipeline-mod-mtm#25] Release version 1.5.1](https://github.com/snaekobbi/pipeline-mod-mtm/pull/25)
- [x] [[pipeline-mod-celia#22] Release version 1.3.0](https://github.com/snaekobbi/pipeline-mod-celia/pull/22)
- [x] [[pipeline-mod-dedicon] Release version 1.5.0#36](https://github.com/snaekobbi/pipeline-mod-dedicon/pull/36)
- [x] [[pipeline-mod-sbs#15] Release version 1.5.0](https://github.com/snaekobbi/pipeline-mod-sbs/pull/15)
- [x] [system] Release version 1.8.0
