### ISSUE TITLE
[3.4:8] The system shall support EPUB 3 as input.

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#174]
### Requirement

[3.4:8] The system shall support EPUB 3 (conforming to the MTM procurement specification) as input.
### Done
- Generic CSS-based EPUB3 to PEF script
- Nota-specific EPUB3 to PEF script (but without CSS)
- NLB-specific EPUB3 to PEF script (but without CSS)
### Todo
- NLB-specific EPUB3 to PEF script with CSS
- MTM-specific EPUB3 to PEF script
  - not CSS-based
  - by porting DTBook to PEF script
  - preparations done?
- Nota-specific EPUB3 to PEF script with CSS
- Celia-specific EPUB3 to PEF script?
- SBS-specific EPUB3 to PEF script?
- Dedicon-specific EPUB3 to PEF script?
### Tasks
- [x] NLB: [[pipeline-mod-nlb#35] EPUB3/HTML support](https://github.com/snaekobbi/pipeline-mod-nlb/issues/35) (@usama49)
- [x] Nota (@stesk, @bertfrees)
- [ ] MTM: Start looking into [[dotify#197] Support epub/html](https://github.com/joeha480/dotify/issues/197) (@bertfrees)
- [ ] system tests
  - [x] NLB ![FAIL](http://snaekobbi.github.io/sprints/FAIL.svg): optimizations needed
  - [ ] Nota ![Ready for test](http://snaekobbi.github.io/sprints/Ready_for_test.svg)
  - [ ] MTM
