### ISSUE TITLE
[4.3:42] The system shall support non-standard hyphenation…

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#178]
### Requirement

[[4.3:42]](http://snaekobbi.github.io/requirements#4.3:42) The system shall support non-standard hyphenation. By non-standard hyphenation we mean that the spelling of a word can change when it is hyphenated. The braille translation of a hyphenated word can only change because the spelling changes, not e.g. because it is contracted in some other way. In other words the definition of non-standard hyphenation is not “extrapolated to braille”.
### Done

Design ready, preparations have been done.
### Tasks
- [x] [[daisy/jhyphen#1] Support non-standard hyphenation](https://github.com/daisy/jhyphen/issues/3) (@bertfrees)
- [x] [[pipeline-mod-braille#55] Support non-standard hyphenation](https://github.com/snaekobbi/pipeline-mod-braille/issues/55) (@bertfrees)
  - Design, refactorings and implementation are done (was a big job!) but still needs debugging and testing.
- [ ] [[pipeline-mod-nlb#38] Non-standard hyphenation patterns](https://github.com/snaekobbi/pipeline-mod-nlb/issues/38) (@usama49, @josteinaj)
- [ ] system test
  - [ ] NLB
