### ISSUE TITLE
[4.7:96] The system shall support automatic insertion of content that is not present in the source…

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#181]
### Requirement

[[4.7:96]](http://snaekobbi.github.io/requirements#4.7:96) The system shall support automatic insertion of content that is not present in the source. Examples include:
- boilerplate text inserted e.g. on the title page,
- metadata and details about the production process,
- automatic transcriber notes that give information about omitted or moved content, about how tables are rendered,
- etc.
### Done
- Table of contents are generated in generic DTBook/EPUB3 to PEF scripts, and styled in agency-specific CSS.
- All agency-specific scripts generate boilerplate such as title pages.
### Todo
- Tweaking of generated boilerplate.

Related but not included here:
- Support more counters/variables on title page: https://github.com/snaekobbi/sprints/issues/160
- Dedicon: symbols list: https://github.com/snaekobbi/sprints/issues/98
### Tasks
- [ ] Tweaking of generated boilerplate in agency-specific scripts (all @snaekobbi/developers that don't have perfect boilerplate yet)
  - [ ] NLB: [[pipeline-mod-nlb#32] Improved or additional generated content](https://github.com/snaekobbi/pipeline-mod-nlb/issues/32) (@usama49)
  - [x] SBS: [[pipeline-mod-sbs#7] Integrate boilerplate part of dtbook2sbsform](https://github.com/snaekobbi/pipeline-mod-sbs/issues/7) (@egli)
- [ ] system tests
  - [ ] SBS ![Ready for test](http://snaekobbi.github.io/sprints/Ready_for_test.svg)
  - [x] NLB
    - Mentioning of contraction grade on title page: ![PASS](http://snaekobbi.github.io/sprints/PASS.svg)
