### ISSUE TITLE
[3.4:8] The system shall support EPUB 3 as input.

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#184]
### Requirement

[3.4:8] The system shall support EPUB 3 (conforming to the MTM procurement specification) as input.
### Tasks
- [x] NLB: [[pipeline-mod-nlb#35] EPUB3/HTML support](https://github.com/snaekobbi/pipeline-mod-nlb/issues/35): optimizations needed (@usama49)
- [ ] MTM: [[dotify#197] Support epub/html](https://github.com/joeha480/dotify/issues/197) (@bertfrees, @joeha480)
- [ ] Celia
- [ ] system tests
  - [ ] MTM: initial implementation ![Ready for test](http://snaekobbi.github.io/sprints/Ready_for_test.svg)
  - [x] NLB
### Test results
- NLB: according to Kari web UI has problems with large files. Don't know whether Kari has tried with smaller files.
- SBS: Mischa put in a "PASS" for the generic EPUB to PEF conversion. There is no SBS-specific conversion yet.
- MTM has not tested and will not have time in sprint#11 either.
