### ISSUE TITLE
Optimize agency-specific scripts

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#187]
### Tasks
- improve generated boilerplate
  - see [4.7:96](https://github.com/snaekobbi/sprints/issues/181)
  - ~~see [4.7:118 (Dedicon symbols list)](https://github.com/snaekobbi/sprints/issues/98)~~
- improve CSS
  - SBS
  - Celia
  - Dedicon
  - Nota
    - [x] List numbering: see [4.7:98](https://github.com/snaekobbi/sprints/issues/78)
  - NLB
    - [x] [[pipeline-mod-nlb#31] Make text alternating on odd and even pages when line-spacing is "double"](https://github.com/snaekobbi/pipeline-mod-nlb/issues/31)
    - [x] [[pipeline-mod-nlb#33] Automatic numbering of notes](https://github.com/snaekobbi/pipeline-mod-nlb/issues/33)
    - [ ] [[pipeline-mod-nlb#34] Support for tables](https://github.com/snaekobbi/pipeline-mod-nlb/issues/34)
- other
  - SBS
    - [x] Optimize translation: see [4.3:38](https://github.com/snaekobbi/sprints/issues/176)
    - [x] "Shrink-to-fit" underlining: see [4.4:50](https://github.com/snaekobbi/sprints/issues/30)
  - Celia
    - [x] [[pipeline-mod-celia#10] There is an excess line break after page breaks in BRF](https://github.com/snaekobbi/pipeline-mod-celia/issues/10)
    - [x] [[pipeline-mod-celia#11] Add copyright symbol to liblouis tables](https://github.com/snaekobbi/pipeline-mod-celia/issues/11)
    - [x] [[pipeline-mod-celia#5] Make all options work](https://github.com/snaekobbi/pipeline-mod-celia/issues/5)
    - [x] ~~[[pipeline-mod-celia#21] The line breaks in generated TOC happen in the wrong places](https://github.com/snaekobbi/pipeline-mod-celia/issues/21)~~
    - [ ] Optimize double letter spacing: see [4.3:36](https://github.com/snaekobbi/sprints/issues/179)
  - Dedicon
  - MTM
    - [x] Leave out capitals: see [4.3:35C](https://github.com/snaekobbi/sprints/issues/185)
    - [x] Leave out styles
    - [x] Print page break indicator: see [4.8:105](https://github.com/snaekobbi/sprints/issues/182)
    - [ ] [[pipeline-mod-mtm#21] Adjust the table layout break point](https://github.com/snaekobbi/pipeline-mod-mtm/issues/21)
    - [x] ~~[[pipeline-mod-mtm#24] Option to choose diacritics handling](https://github.com/snaekobbi/pipeline-mod-mtm/issues/24)~~
  - Nota
    - [ ] [[pipeline-mod-nota#8] Restrict conversion of emphasis](https://github.com/snaekobbi/pipeline-mod-nota/issues/8)
  - NLB
    - [ ] Non-standard hyphenation: see [4.3:42](https://github.com/snaekobbi/sprints/issues/178)
- system tests
  - NLB (ready: see [release notes](https://github.com/snaekobbi/pipeline-mod-nlb/releases/tag/v1.8.0))
    - Make text alternating on odd and even pages when line-spacing is "double": ![FAIL](http://snaekobbi.github.io/sprints/FAIL.svg) (https://github.com/snaekobbi/pipeline-mod-nlb/issues/41)
    - Automatic numbering of notes: ![PASS](http://snaekobbi.github.io/sprints/PASS.svg)
    - Fixes to liblouis translation (https://github.com/snaekobbi/pipeline-mod-nlb/issues/36)
      - sami reverse circumflex: ![FAIL](http://snaekobbi.github.io/sprints/FAIL.svg)
      - a with acute: ![PASS](http://snaekobbi.github.io/sprints/PASS.svg)
      - long and short dash: ![FAIL](http://snaekobbi.github.io/sprints/FAIL.svg)
  - Nota ![Ready for test](http://snaekobbi.github.io/sprints/Ready_for_test.svg) (see [release notes](https://github.com/snaekobbi/pipeline-mod-nota/releases/tag/v1.3.0))
  - SBS (ready: see [release notes](https://github.com/snaekobbi/pipeline-mod-sbs/releases/tag/v1.5.0)): ![PASS](http://snaekobbi.github.io/sprints/PASS.svg)
    - but new bug with print page numbers
  - Celia ![Ready for test](http://snaekobbi.github.io/sprints/Ready_for_test.svg) (see [release notes](https://github.com/snaekobbi/pipeline-mod-celia/releases/tag/v1.3.0))
  - MTM

**Comment by bertfrees** [comment]
@snaekobbi/developers Please make sure everything you want to include in the next release, which I will make on Monday, is on the master branch or in a pull request.
