### ISSUE TITLE
[3.6:20] The server side of the system shall run on the Windows platform.

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#188]
### Requirement

[3.6:20] The server side of the system shall run on the Windows platform.
### Tasks
- [x] [[pipeline-webui#64] Create distributable for Windows](https://github.com/daisy/pipeline-webui/issues/64) (@josteinaj)
- [ ] Look into various Windows-related bugs in the engine (@bertfrees)
  - [x] [[pipeline-mod-dedicon#25] Support hyphenation on Windows](https://github.com/snaekobbi/pipeline-mod-dedicon/issues/25)
  - [x] [[daisy/pipeline-mod-braille#107] Build and include libhyphen.dll](https://github.com/daisy/pipeline-mod-braille/issues/107)
  - [ ] [[pipeline-mod-dedicon#24] Look into failing inline CSS step](https://github.com/snaekobbi/pipeline-mod-dedicon/issues/24)
  - [ ] [[jStyleParser#5] Fix encoding problem which exists on some systems](https://github.com/snaekobbi/jStyleParser/issues/5)
  - [x] [[daisy/pipeline-assembly#103] Temporary workaround for encoding issues](https://github.com/daisy/pipeline-assembly/issues/103)
  - [x] [[daisy/pipeline-mod-braille#50] CSS rule ignored if BOM (byte order mark) present](https://github.com/daisy/pipeline-mod-braille/issues/50)
- [ ] [[system#9] Add Windows playbook and test VM](https://github.com/snaekobbi/system/issues/9) (@bertfrees)
  - Ammar has already done some preparation
- [ ] test Windows distributables
  - [ ] Celia (engine tested)
  - [ ] Dedicon

**Comment by dkager** [comment]
This will eventually include providing a Windows distributable that non-developers can deploy and use, e.g. MSI.

**Comment by josteinaj** [comment]
@dkager By "non-developers" do you also mean "non-sysadmins"? The Web UI is only intended to be installed on servers, and is not intended to be installed by end-users.

**Comment by dkager** [comment]
No, I mean sysadmins, but those who don’t want to use Maven or other such tools to prepare the binaries. The zip-file that pipeline-assembly can build looks good already.

**Comment by josteinaj** [comment]
Ok, good :).
