### ISSUE TITLE
Improve usability

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#190]
### Tasks
- Various web UI optimizations (@josteinaj)
  - [x] [[pipeline-webui#50] started/finished time not showing when refreshing job view](https://github.com/daisy/pipeline-webui/issues/50)
  - [x] [[pipeline-webui#70] Fix whitespace in markdown descriptions](https://github.com/daisy/pipeline-webui/issues/70)
  - [x] [[pipeline-webui#36] use "job started" instead of "job created" in job listing](https://github.com/daisy/pipeline-webui/issues/36)
  - [x] [[pipeline-webui#80] Unable to start job after attempting to start with invalid regex type option](https://github.com/daisy/pipeline-webui/issues/80)
  - [x] [[pipeline-webui#85] Remove top-level "option name"-directories](https://github.com/daisy/pipeline-webui/issues/85)
  - [x] [[pipeline-webui#86] Results button for filesets containing HTML files should link directly to the HTML](https://github.com/daisy/pipeline-webui/issues/86)
  - [x] [[pipeline-webui#87] Remove the "results" section from the job view](https://github.com/daisy/pipeline-webui/issues/87)
  - [x] [[pipeline-webui#76] Detailed descriptions for options should be hidden by default](https://github.com/daisy/pipeline-webui/issues/76)
  - [ ] [[pipeline-webui#90] Non-ASCII characters dropped from user names in jobs listing ](https://github.com/daisy/pipeline-webui/issues/90)
  - [x] [[pipeline-webui#89] Implement progressbar](https://github.com/daisy/pipeline-webui/issues/89)
  - [ ] [[pipeline-webui#77] support documentation in regex datatype](https://github.com/daisy/pipeline-webui/issues/77)
  - [x] [[pipeline-webui#61] In the job view; if the job is not found in the engine, give a friendly message saying so](https://github.com/daisy/pipeline-webui/issues/61)
  - ...

Related:
- [Improve performance](https://github.com/snaekobbi/sprints/issues/189)
