### ISSUE TITLE
Improve usability

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#191]
### Tasks
- [ ] more useful job messages
  - [x] [[daisy/pipeline-mod-braille#80] Warning vs. error when a certain feature is not supported](https://github.com/daisy/pipeline-mod-braille/issues/80)
  - [ ] [[daisy/pipeline-mod-braille#89] More useful feedback from validation in dotify:xml-to-obfl](https://github.com/daisy/pipeline-mod-braille/issues/89): done, waiting for startup issues to be fixed
  - [ ] [[daisy/pipeline-mod-braille#41] Give warning messages for CSS properties/values that are not supported by the implementation](https://github.com/daisy/pipeline-mod-braille/issues/41)
  - [x] [[daisy/pipeline-mod-braille#38] Fix XSLT warnings that looks like errors](https://github.com/daisy/pipeline-mod-braille/issues/38): done for now until we find a solution for the last two kinds of warnings
  - [x] "Ambiguous rule match"
  - [x] "Evaluation will always fail"
  - [x] "Included more than once"
  - [ ] "Document has namespace X but stylesheet has no templates in that namespace"
  - [x] "The source document is in no namespace, but the template rules all expect elements in a namespace"
  - [ ] [[daisy/pipeline-mod-braille#19] Proper logging](https://github.com/daisy/pipeline-mod-braille/issues/19)
  - [ ] [[daisy/pipeline-mod-braille#36] Jobs says "Success" but no output](https://github.com/daisy/pipeline-mod-braille/issues/36)
  - [ ] [[pipeline-assembly#87] jul-to-slf4j bridge](https://github.com/daisy/pipeline-assembly/issues/87): waiting for startup issues to be fixed
- [ ] progress messages (see https://github.com/daisy/pipeline-issues/issues/445)
- [ ] optimize pef preview (@bertfrees)
  - [ ] [[daisy/pipeline-mod-braille#87] PEF preview not showing volume division](https://github.com/daisy/pipeline-mod-braille/issues/87)
### Possible future tasks
- [ ] CSS debugging tool
  - [ ] [[daisy/pipeline-mod-braille#91] Option include-css](https://github.com/daisy/pipeline-mod-braille/issues/91)
  - [ ] [[daisy/pipeline-mod-braille#101] XProc function for deep parsing and cascading](https://github.com/daisy/pipeline-mod-braille/issues/101)
- [ ] table authoring tool (@stesk?)

Related:
- [Documentation](https://github.com/snaekobbi/sprints/issues/193)
