### ISSUE TITLE
Improve maintainability

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#192]
### Tasks
- Cleanup and organisation of code
  - [ ] [[issues#31] Move repos to other organisations or archive them](https://github.com/snaekobbi/issues/issues/31)
- Organize/optimize development and release process
  - [ ] [[daisy/pipeline-tasks#34] Create aggregator projects](https://github.com/daisy/pipeline-tasks/issues/34)
  - [x] [[daisy/pipeline-tasks#32 Branching pattern](https://github.com/daisy/pipeline-tasks/issues/32)
  - [ ] [[daisy/pipeline-assembly#75] POM clean up](https://github.com/daisy/pipeline-assembly/issues/75)
- Think about portability (decoupling from Pipeline)
  - [ ] [[daisy/pipeline-tasks#33] Replace Require-Bundle with a better (custom) system for wiring up (non-Java) components](https://github.com/daisy/pipeline-tasks/issues/33)
  - [ ] [[daisy/pipeline-tasks#31] Remove dependency on some OSGi features](https://github.com/daisy/pipeline-tasks/issues/31)
### Possible future tasks
- Think about compatibility (between specs, between APIs, between components)
  - specs: e.g. OBFL vs. braille CSS
  - APIs: e.g. common braille translator API

Related:
- [Performance](https://github.com/snaekobbi/sprints/issues/189) (running tests)
- [Documentation](https://github.com/snaekobbi/sprints/issues/193) (developer documentation, github issues)
