### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#193]
### Tasks
- [ ] finish braille-css spec, make sure all pending issues are covered by the spec (@bertfrees)
- [ ] work on OBFL spec (@bertfrees)
- [ ] improve script and template documentation (@snaekobbi/experts)
- [ ] finish developer docs and website (@bertfrees)
- [ ] finish showcase (http://snaekobbi.github.io/requirements/, importance for visibility of project towards new partners) (@bertfrees, @snaekobbi/developers)
- [ ] for all pending Github issues provide enough information in order for others to fix them
