### ISSUE TITLE
[4.5:82] The header and footer layout shall be able to change between sections within the document.

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#197]
### Requirement

[[4.5:82]](http://snaekobbi.github.io/requirements#4.5:82) The header and footer layout shall be able to change between sections within the document.
### Tasks
- [x] [[daisy/pipeline-mod-braille#104] Allow page property on elements that are flowed into volume @begin or @end area](https://github.com/daisy/pipeline-mod-braille/issues/104)
- [ ] adapt CSS in pipeline-mod-sbs + test (@egli)
- [x] system test: @mixa72: ![](http://snaekobbi.github.io/sprints/PASS.svg)
### Test result
- SBS: addtitionally, braille page numbers need to be resetable and roman in the toc.
  - [[pipeline-mod-braille#121] Support counter-set:page inside @begin and @end areas](https://github.com/daisy/pipeline-mod-braille/issues/121)

**Comment by bertfrees** [comment]
@mixa72 I don't think you mentioned the "roman in the toc" before. What exactly do you mean by that?
