### ISSUE TITLE
[4.7:102] The system shall be able to evaluate certain variables and counters at so-called fields…

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#198]
### Requirement

[[4.7:102]](http://snaekobbi.github.io/requirements#4.7:102) The system shall be able to evaluate certain variables and counters at so-called "fields", for example on the title page or in the page header or footer. Supported variables shall include at least the current braille page number, the current print page number or range of print pages contained in the current braille page, the current volume number, the total number of volumes, the total number of braille pages or sheets contained in the current volume or book, the current chapter title, the current chapter number, and the date.
### Tasks
- [x] Implement variables for total number of braille pages or sheets contained in the current volume or book: see https://github.com/daisy/pipeline-mod-braille/commit/cfbeff24ba35e0b674275098c685918f698b691c
- [ ] [[daisy/pipeline-mod-braille#110] Fix string-set and string() within named flows](https://github.com/daisy/pipeline-mod-braille/issues/110)
- [ ] system test
  - [x] NLB (see [4.7:96](https://github.com/snaekobbi/sprints/issues/203)): ![](http://snaekobbi.github.io/sprints/PASS.svg)
  - [ ] SBS
