### ISSUE TITLE
[4.1:25] The system shall support editing on block level in order to fix wrong translations…

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#2]
### Requirement

[[4.1:25]](http://snaekobbi.github.io/requirements#4.1:25) The system shall support editing on block level in order to fix wrong translations, e.g. in the case of complex material such as mathematics. It is assumed that all other improvements outside blocks can be accomplished by changing the input document.
### Done
- `include-obfl` has been added: https://github.com/daisy/pipeline-mod-braille/issues/90
### Todo
- Come up with a file format that can capture all the state (originating from input options and internal data from the first part of the conversion) that the second part of the conversion (OBFL to PEF) needs in order to finish the conversion. The file format will probably be a ZIP file with the OBFL and another XML file for the state.
- "Editing format" to PEF script (i.e. second part of conversion)
- Option for forcing pre-translation because an editing file is most useful when translation has been performed.
### Tasks
- [ ] specify editing format (@bertfrees)
- [ ] implement editing format (@bertfrees)
- [ ] script for "finalizing" an edited file (OBFL to PEF) (@bertfrees)
- [ ] basic Oxygen authoring mode for OBFL (@jukkae) (related to https://github.com/joeha480/dotify/issues/85)
- [ ] test (all @snaekobbi/experts?)
