### ISSUE TITLE
Optimize agency-specific scripts

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#200]
### Tasks
- NLB
  - [ ] [[pipeline-mod-nlb#32] Improved or additional generated content](https://github.com/snaekobbi/pipeline-mod-nlb/issues/32) (see [4.7:96](https://github.com/snaekobbi/sprints/issues/203))
  - [x] [[pipeline-mod-nlb#36] Some fixes to norwegian table (sami reverse circumlex, sami vs norse acute, dashes)](https://github.com/snaekobbi/pipeline-mod-nlb/issues/36)
  - [ ] [[pipeline-mod-nlb#34] Support for tables](https://github.com/snaekobbi/pipeline-mod-nlb/issues/34)
  - [x] [[pipeline-mod-nlb#38] Non-standard hyphenation patterns](https://github.com/snaekobbi/pipeline-mod-nlb/issues/38) (see [4.3:42](https://github.com/snaekobbi/sprints/issues/204))
  - [x] [[pipeline-mod-nlb#35] EPUB3/HTML support](https://github.com/snaekobbi/pipeline-mod-nlb/issues/35) (see [3.4:8](https://github.com/snaekobbi/sprints/issues/184))
  - [x] [[pipeline-mod-nlb#42] Either implement or hide unimplemented options ](https://github.com/snaekobbi/pipeline-mod-nlb/issues/42)
  - [ ] [[pipeline-mod-nlb#41] Title page and colophon should never have double line spacing](https://github.com/snaekobbi/pipeline-mod-nlb/issues/41)
- SBS
  - [x] [[pipeline-mod-sbs#18] Fix underlining of headings](https://github.com/snaekobbi/pipeline-mod-sbs/issues/18) (see [4.4:50](https://github.com/snaekobbi/sprints/issues/202))
  - [x] [[pipeline-mod-sbs#16] Fix print page number](https://github.com/snaekobbi/pipeline-mod-sbs/issues/16)
  - [x] [[pipeline-mod-sbs#17] Volume numbers](https://github.com/snaekobbi/pipeline-mod-sbs/issues/17)
- MTM
  - [ ] [[pipeline-mod-mtm#21] Adjust the table layout break point](https://github.com/snaekobbi/pipeline-mod-mtm/issues/21)
- Celia
  - [ ] [[pipeline-mod-celia#25] Double letter spacing fixes](https://github.com/snaekobbi/pipeline-mod-celia/issues/25) (see [4.3:36](https://github.com/snaekobbi/sprints/issues/201))
  - [ ] [[pipeline-mod-celia#28] Various smaller CSS and table fixes](https://github.com/snaekobbi/pipeline-mod-celia/issues/28)
  - [x] [[pipeline-mod-celia#27] TOCs: Need for book-level TOC as well?](https://github.com/snaekobbi/pipeline-mod-celia/issues/27)
- Nota
  - [ ] [[pipeline-mod-nota#15] Grade 1 (partly contracted)](https://github.com/snaekobbi/pipeline-mod-nota/issues/15) (see [4.3:37](https://github.com/snaekobbi/sprints/issues/177))
- Dedicon
  - [ ] [[pipeline-mod-dedicon#40] Table of contents in backmatter of last volume](https://github.com/snaekobbi/pipeline-mod-dedicon/issues/40)
  - [x] [[pipeline-mod-dedicon#41] Volume headings in document scope TOC](https://github.com/snaekobbi/pipeline-mod-dedicon/issues/41)
  - [ ] [Clean up options (also generic script)](https://github.com/snaekobbi/pipeline-mod-dedicon/issues/23)
- system tests, including features that have been implemented in [sprint#9](https://github.com/snaekobbi/sprints/issues/187) but not tested yet
  - NLB ![Ready for test](http://snaekobbi.github.io/sprints/Ready_for_test.svg): generated content (see [4.7:96](https://github.com/snaekobbi/sprints/issues/203)), table fixes, non-standard hyphenation (see [4.3:42](https://github.com/snaekobbi/sprints/issues/204)), epub fixes (see [3.4:8](https://github.com/snaekobbi/sprints/issues/184)), title page and colophon line spacing)
  - SBS ![Ready for test](http://snaekobbi.github.io/sprints/Ready_for_test.svg)
  - MTM
  - Nota
