### ISSUE TITLE
[4.4:50] There shall be the possibility of shrinking a block with a border to the size of its contents…

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#202]
### Requirement

[[4.4:50]](http://snaekobbi.github.io/requirements#4.4:50) There shall be the possibility of shrinking a block with a border to the size of its contents. This feature shall be supported at least for blocks ~~with left-aligned text and~~ no nested blocks.
### Tasks
- [x] [[dotify#50] New OBFL feature for underlining a block of text](https://github.com/braillespecs/obfl/issues/50): add feature to specification based on proposal
- [x] implement feature in Dotify
  - [x] https://github.com/brailleapps/dotify.api/pull/2
  - [x] https://github.com/joeha480/dotify/pull/208
- [x] support in CSS (possibly just another "-obfl-" prefixed property)
- [x] implement in pipeline-mod-braille
- [x] [[pipeline-mod-sbs#18] Fix underlining of headings](https://github.com/snaekobbi/pipeline-mod-sbs/issues/18)
- [x] system test: @mixa72: ![](http://snaekobbi.github.io/sprints/PASS.svg)
### Test results:
- SBS: [[pipeline-mod-sbs#32] When a heading wraps to the next line, the underlining might be one cell too long](https://github.com/sbsdev/pipeline-mod-sbs/issues/32)
