### ISSUE TITLE
[4.7:96] The system shall support automatic insertion of content that is not present in the source…

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#203]
### Requirement

[[4.7:96]](http://snaekobbi.github.io/requirements#4.7:96) The system shall support automatic insertion of content that is not present in the source. Examples include:
- boilerplate text inserted e.g. on the title page,
- metadata and details about the production process,
- automatic transcriber notes that give information about omitted or moved content, about how tables are rendered,
- etc.
### Tasks
- [ ] [[pipeline-mod-nlb#32] Improved or additional generated content](https://github.com/snaekobbi/pipeline-mod-nlb/issues/32)
- [x] system tes
  - [x] NLB: ![](http://snaekobbi.github.io/sprints/PASS.svg) (total number of braille sheets, title page layout)
  - [x] SBS: ![](http://snaekobbi.github.io/sprints/PASS.svg) (updates to SBS generated content)
### Test results
- The system test passed for Kari for the features that were ready, however there were some things left to do.
