### ISSUE TITLE
[3.5:15] The system shall be able to output plain text using a user-specified braille table and form feed character.

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#208]
### Requirement

[3.5:15] The system shall be able to output plain text using a user-specified braille table and form feed character.
### Tasks
- [x] finish [[daisy/pipeline-mod-braille#103] More control over BRF output required](https://github.com/daisy/pipeline-mod-braille/issues/103)
- [x] [[brailleutils#66] Make a release that includes Braillo NL 6 DOT (031.01) table](https://github.com/joeha480/brailleutils/issues/66) (@joeha480)
- [x] [[pipeline-mod-dedicon#21] Add option to specify BRF filename](https://github.com/snaekobbi/pipeline-mod-dedicon/issues/21)
- [x] test new Braillo table by creating BRF from it and send to embosser (@dkager)
- [x] system test @mixa72: ![FAIL](http://snaekobbi.github.io/sprints/FAIL.svg)
### Test result
- Dedicon: According to Davy the character mapping of the Braillo NL 6 DOT (031.01) needs some adjustments: https://github.com/snaekobbi/pipeline-mod-dedicon/issues/44
- SBS: part of character mapping not correct when using SBS script: https://github.com/snaekobbi/pipeline-mod-sbs/issues/22
