### ISSUE TITLE
[4.3:41] The system shall be able to perform automatic hyphenation for uncontracted and contracted braille.

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#21]
### Requirement

[[4.3:41]](http://snaekobbi.github.io/requirements#4.3:41) The system shall be able to perform automatic hyphenation for uncontracted and contracted braille.
### Tasks
- [x] update requirement (@bertfrees)
  - [ ] [[requirements#8] Tests for Danish hyphenation](https://github.com/snaekobbi/requirements/issues/8)
  - [x] [[requirements#9] Tests for Finnish hyphenation](https://github.com/snaekobbi/requirements/issues/9)
  - [ ] [[requirements#10] Tests for Swedish hyphenation](https://github.com/snaekobbi/requirements/issues/10)
  - [x] [[requirements#11] Tests for Norwegian hyphenation](https://github.com/snaekobbi/requirements/issues/11)
  - [ ] [[requirements#12] Tests for German (Swiss) hyphenation](https://github.com/snaekobbi/requirements/issues/12)
  - [x] [[requirements#43] Tests for Dutch hyphenation](https://github.com/snaekobbi/requirements/issues/43)
- [x] integration (@bertfrees 2h)
  - [x] [[issues#12] Pipeline braille module per agency](https://github.com/snaekobbi/issues/issues/12)
  - [x] [[issues#14] Higher level translator components for all languages](https://github.com/snaekobbi/issues/issues/14)
- [x] provide test data
  - [x] German (@mixa72 2hr)
  - [ ] Danish (@stesk 2hr)
  - [ ] Swedish (@joeha480 2hr)
  - [ ] Finnish (@paivis 2hr)
  - [x] Norwegian (@KariRudjord 2hr)
  - [ ] Dutch (@dkager 2hr)
- [x] execute system tests
  - [x] German (@mixa72 2hr) ![FAIL](http://snaekobbi.github.io/sprints/FAIL.svg)
  - [ ] Danish (@stesk 2hr) ![Ready for test](http://snaekobbi.github.io/sprints/Ready_for_test.svg)
  - [ ] Swedish (@joeha480 2hr) ![Ready for test](http://snaekobbi.github.io/sprints/Ready_for_test.svg)
  - [ ] Finnish (@paivis 2hr) ![Ready for test](http://snaekobbi.github.io/sprints/Ready_for_test.svg)
  - [ ] Norwegian (@KariRudjord 2hr) ![Ready for test](http://snaekobbi.github.io/sprints/Ready_for_test.svg)
  - [ ] Dutch (@dkager 2hr) ![Ready for test](http://snaekobbi.github.io/sprints/Ready_for_test.svg)
### Test results
- [System Test protocol_Braille DP2 v1.0_DE.xlsx
  ](https://github.com/snaekobbi/testing/blob/master/Test%20protocol/Sprint_1
  /DE/System%20Test%20protocol_Braille%20DP2%20v1.0_DE.xlsx?raw=true)
#### Issues
- [[system#2] System should start up properly each time](https://github.com/snaekobbi/system/issues/2)
- [[daisy/pipeline-webui#26] Job page keeps showing "Running..."](https://github.com/daisy/pipeline-webui/issues/26)
