### ISSUE TITLE
Optimize agency-specific scripts

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#211]
### Tasks

Final tweaks to agency-specific scripts
- [ ] [NLB](https://github.com/snaekobbi/pipeline-mod-nlb/issues) (@usama49)
- [ ] [Dedicon](https://github.com/snaekobbi/pipeline-mod-dedicon/issues) (@dkager)
- [ ] [Celia](https://github.com/snaekobbi/pipeline-mod-celia/issues) (@jukkae)
