### ISSUE TITLE
Improve usability

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#216]
### Tasks
- [ ] finish work on job messages
- [ ] finish work on progress messages
- [x] [[daisy/pipeline-mod-braille#87] PEF preview not showing volume division](https://github.com/daisy/pipeline-mod-braille/issues/87)
- [ ] system test: @stesk
