### ISSUE TITLE
[4.3:44] The user shall be able to make a top-level configuration…

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#24]
### Requirement

[[4.3:44]](http://snaekobbi.github.io/requirements#4.3:44) The user shall be able to make a top-level configuration, e.g. toggle hyphenation.
### Tasks

Finalize scripts including default CSS and implementation of all options.
- [x] SASS support (@bertfrees)
- [x] create SASS style sheet
  - [x] [SBS](https://github.com/snaekobbi/pipeline-mod-sbs/blob/master/src/main/resources/css/default.scss) (@egli)
  - [x] [Dedicon](https://github.com/snaekobbi/pipeline-mod-dedicon/blob/master/src/main/resources/css/dedicon-default.scss) (@dkager)
  - [x] [NLB](https://github.com/snaekobbi/pipeline-mod-nlb/blob/master/src/main/resources/css/nlb-default.scss) (@usama49)
  - [x] [Celia](https://github.com/snaekobbi/pipeline-mod-celia/blob/master/src/main/resources/css/celia-default.scss) (@jukkae)
  - [x] [Nota](https://github.com/snaekobbi/pipeline-mod-nota/blob/master/src/main/resources/css/default.scss) (@stesk)
- [ ] implement options as defined in https://github.com/snaekobbi/issues/issues/22, using SASS/XProc/XSLT
  - [x] generic script (@bertfrees): the ones that are left are either unclear, are maybe not needed, depend on unimplemented features or just need work.
  - [x] MTM script (@bertfrees, @joeha480): some option left, Joel is going to look at them
  - [ ] NLB script: https://github.com/snaekobbi/pipeline-mod-nlb/issues/29
  - [x] Celia script: https://github.com/snaekobbi/pipeline-mod-celia/issues/5
  - [ ] Dedicon script: https://github.com/snaekobbi/pipeline-mod-dedicon/issues/23
  - [ ] Nota script: https://github.com/snaekobbi/pipeline-mod-nota/issues/4
  - [ ] SBS script: https://github.com/snaekobbi/pipeline-mod-sbs/issues/10
- [ ] unit tests for options
  - [x] generic (@bertfrees)
  - [ ] SBS (@egli): https://github.com/snaekobbi/pipeline-mod-sbs/issues/8
  - [ ] Dedicon (@dkager): https://github.com/snaekobbi/pipeline-mod-dedicon/issues/23
  - [ ] NLB (@usama49, @josteinaj): https://github.com/snaekobbi/pipeline-mod-nlb/issues/24, https://github.com/snaekobbi/pipeline-mod-nlb/issues/29
  - [x] Celia (@jukkae): https://github.com/snaekobbi/pipeline-mod-celia/issues/4, https://github.com/snaekobbi/pipeline-mod-celia/issues/5
  - [ ] MTM: https://github.com/snaekobbi/pipeline-mod-mtm/issues/17
  - [ ] Nota: https://github.com/snaekobbi/pipeline-mod-nota/issues/4
- [ ] system tests
  - [ ] @BWestling ![Ready for test](http://snaekobbi.github.io/sprints/Ready_for_test.svg)
  - [ ] @JC-MTM ![Ready for test](http://snaekobbi.github.io/sprints/Ready_for_test.svg)
  - [x] @stesk ![PASS](http://snaekobbi.github.io/sprints/PASS.svg)
  - [x] @KariRudjord ![FAIL](http://snaekobbi.github.io/sprints/FAIL.svg)
### Test results
- Some irregularities between NLB CSS and GUI. Ammar has updated nlb-default.css, but need to be tested again when system is updated: https://github.com/snaekobbi/pipeline-mod-nlb/issues/29
