### ISSUE TITLE
[4.4:48] By default margins shall be collapsing. However there shall be a way to override this behaviour.

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#28]
### Requirement

[[4.4:48]](http://snaekobbi.github.io/requirements#4.4:48) By default margins shall be collapsing. However there shall be a way to override this behaviour.
### Tasks
- [ ] update requirement (@bertfrees)
  - [ ] [[requirements#14] Tests for collapsing margins](https://github.com/snaekobbi/requirements/issues/14)
  - [ ] consider splitting requirement into part 1 and 2
- [x] specification
  - [x] [[joeha480/obfl#27] Support collapsing margins](https://github.com/joeha480/obfl/issues/27) (@joeha480)
  - [x] [[joeha480/obfl#29] Add padding property](https://github.com/joeha480/obfl/issues/29) (@joeha480)
- [ ] implementation
  - [x] [dotify] Support collapsing margins
  - [ ] [[pipeline-mod-braille#30] Support collapsing margins](https://github.com/snaekobbi/pipeline-mod-braille/issues/30) (@bertfrees + @joeha480)
- [ ] provide test data (@mixa72, @stesk, @KariRudjord, @paivis, @JC-MTM, @dkager)
