### ISSUE TITLE
[4.4:53] The system shall support block alignment relative to a vertical position on the page.

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#33]
### Requirement

[[4.4:53]](http://snaekobbi.github.io/requirements#4.4:53) The system shall support block alignment relative to a vertical position on the page.
### Tasks
- [ ] finalise requirement: [[requirements#16] Tests for vertical positioning](https://github.com/snaekobbi/requirements/pull/16)
- [ ] specification: [[braille-css-spec#20] Vertical positioning](https://github.com/snaekobbi/braille-css-spec/issues/20) (@bertfrees 2.5h, @joeha480 2.5h)
- [ ] implementation: [[pipeline-mod-braille#28] Support vertical positioning](https://github.com/snaekobbi/pipeline-mod-braille/issues/28) (@bertfrees 4h)
- [ ] provide test data (@mixa72, @stesk, @KariRudjord, @paivis, @JC-MTM, @dkager)
