### ISSUE TITLE
[4.4:55] The user shall be able to override the default handling of whitespace for certain elements…

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#35]
### Requirement

[[4.4:55]](http://snaekobbi.github.io/requirements#4.4:55) The user shall be able to override the default handling of whitespace for certain elements:
- Prevent collapsing of sequences of whitespace.
- Preserve leading and trailing whitespace inside block elements.
- Preserve newline characters as forced line breaks.
### Tasks
- [x] finalise requirement: [[requirements#17] Tests for white space handling](https://github.com/snaekobbi/requirements/pull/17) (@bertfrees)
- [x] specification: [[braille-css-spec#30] White space processing and line breaking](https://github.com/snaekobbi/braille-css-spec/issues/30) (@bertfrees)
- [x] implementation: [[pipeline-mod-braille#52] Make braille translator contract more strict with respect to white space](https://github.com/snaekobbi/pipeline-mod-braille/issues/52) (@bertfrees)
- [x] provide test data
  - [x] @mixa72
  - [x] @KariRudjord (https://github.com/snaekobbi/testing/pull/1)
  - [x] @stesk
- [x] write test cases (@denisviro)
- [ ] execute system tests
  - [x] @mixa72 ![FAIL](http://snaekobbi.github.io/sprints/FAIL.svg)
  - [ ] @KariRudjord ![Ready for test](http://snaekobbi.github.io/sprints/Ready_for_test.svg)
  - [x] @stesk ![FAIL](http://snaekobbi.github.io/sprints/FAIL.svg)
### Test results
- [DK](https://github.com/snaekobbi/testing/blob/master/Test%20protocol/Sprint_2/DK/System%20Test%20protocol_Braille%20DP2_Sprint%202_DK.xlsx?raw=true): The final newline in the paragraph is ignored when the CSS property is set to `pre-wrap`. The same newline forces a break (as expected) when the property is set to `pre-line`. Otherwise `pre-wrap` and `pre-line` works as this tester would expect them to work. I note that neither property is automatically applied to the `<pre>` element; maybe this should be in the default stylesheet?
- [DE](https://github.com/snaekobbi/testing/blob/master/Test%20protocol/Sprint_2/DE/System%20Test%20protocol_Braille%20DP2_Sprint%202_DE.xlsx?raw=true): no double spaces in the output
#### Issues
- [x] `white-space: pre-wrap|pre-line` not working for long text (fixed in commit https://github.com/daisy/pipeline-mod-braille/commit/6b25e5388637ce46c2e6c4bdcd71fc6475a34637)
- [ ] [[sbsdev/sbs-braille-tables#1] Make tables more "white space aware"](https://github.com/sbsdev/sbs-braille-tables/issues/1)

**Comment by bertfrees** [comment]
@stesk The issue with the last bracket not being rendered on a new line is solved in the code (fix will be available in system v1.2).
