### ISSUE TITLE
[4.4:57] There shall be the option to reformat a table into a list…

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#36]
### Requirement

[[4.4:57]](http://snaekobbi.github.io/requirements#4.4:57) There shall be the option to reformat a table into a list,
- either by linearizing the table row-by-row with delimiters between cells,
- or by rendering each row as a sublist, where the cells are the list items. It must be possible to set off cells with a left margin according to their column, so that a stairstep format can be accomplished.
- It must be possible to prepend cells with their column header.
### Tasks
- [ ] CSS specificiation (@bertfrees)
- [x] implementation (@bertfrees)
- [ ] system tests
  - [x] @mixa72 ![FAIL](http://snaekobbi.github.io/sprints/FAIL.svg)
  - [x] @stesk ![PASS](http://snaekobbi.github.io/sprints/PASS.svg)
  - [ ] @JC-MTM, @BWestling ![Ready for test](http://snaekobbi.github.io/sprints/Ready_for_test.svg)
  - [ ] @KariRudjord ![Ready for test](http://snaekobbi.github.io/sprints/Ready_for_test.svg)
  - [ ] @paivis ![Ready for test](http://snaekobbi.github.io/sprints/Ready_for_test.svg)
### Test results
- DE: "fail: test_4.4.57_ex1_row-by-row (table-footer not working properly)"
  - I'm not sure what Mischa means by this. There was the issue that `tfoot` wasn't rendered at the bottom but that has been resolved. I also added the predefined axis "row-group" so that cells can be grouped according to (thead,) tbody and tfoot elements, which can for example be used to create a border between body and footer, or between several tbody elements. (**ISSUE RESOLVED**)
### Issues/suggestions
- [x] Make "column" an alias of the "col" axis.
- [x] Support styling of promoted header groups.
- [x] When searching for headers when the col(umn) axis was applied (before row), search upwards first and then left.
- [ ] Support additional axes "column-header" and "row-header" that use some heuristic to discover column or row headers.
- [ ] Issue with white space only text nodes that are removed from css:render-table-by output.
- [ ] Support merged data cells.
- [x] Support `:first-child`, `nth-child()` etc. on `::list-item` pseudo-element.
- [ ] Support `table-header-policy: front` across multiple levels.
- [ ] Automatically swap tfoot and tbody elements so that the original table structure can be preserved if needed (i.e. skip `render-table-by` altogether).
