### ISSUE TITLE
[4.4:56] The system shall provide a way to control the layout of each table separately.

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#39]
### Requirement

[[4.4:56]](http://snaekobbi.github.io/requirements#4.4:56) The system shall provide a way to control the layout of each table separately.
### Tasks
- [ ] CSS specificiation
  - [ ] matrix tables
  - [ ] tables as lists
- [ ] CSS implementation (@bertfrees)
  - [ ] matrix tables
  - [x] tables as lists
- [ ] system tests
  - [x] @mixa72 ![PASS](http://snaekobbi.github.io/sprints/PASS.svg)
  - [x] @stesk ![PASS](http://snaekobbi.github.io/sprints/PASS.svg)
  - [ ] @JC-MTM, @BWestling ![Ready for test](http://snaekobbi.github.io/sprints/Ready_for_test.svg)
  - [ ] @KariRudjord ![Ready for test](http://snaekobbi.github.io/sprints/Ready_for_test.svg)
  - [ ] @paivis ![Ready for test](http://snaekobbi.github.io/sprints/Ready_for_test.svg)
