### ISSUE TITLE
[4.4:62] The system shall be able to cope with column- and rowspan in tables…

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#43]
### Requirement

[[4.4:62]](http://snaekobbi.github.io/requirements#4.4:62) The system shall be able to cope with column- and rowspan in tables (in a yet undefined way).
### Tasks
- [x] system tests: (see also https://github.com/snaekobbi/sprints/issues/167 and https://github.com/snaekobbi/sprints/issues/168)
  - [x] @mixa ![FAIL](http://snaekobbi.github.io/sprints/FAIL.svg)
  - [x] @stesk ![FAIL](http://snaekobbi.github.io/sprints/FAIL.svg)
### Test results
- DE: third underlining in rowspan is too long
- DK: Works for header cells, but fails for data cells. I'm upgrading the priority on this issue, as support for merged data cells is a definite requirement for us. ![priority:1](http://snaekobbi.github.io/sprints/priority_1.svg)

**Comment by bertfrees** [comment]
Added this to sprint 8 because it is ready for test, so it can be included if testers wish to do so.

**Comment by bertfrees** [comment]
Added support for rowspan and colspan in data cells.

**Comment by bertfrees** [comment]
> third underlining in rowspan is too long

@mixa72: what exactly was the issue?

**Comment by mixa72** [comment]
actual:

```
⠍⠕⠝⠁⠞⠀⠀⠀⠀⠑⠗⠎⠏⠁⠗⠝⠊⠎⠀⠀⠑⠗⠎⠏⠁⠗⠝⠊⠎⠀⠋⠑⠗⠊⠑⠝⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠒⠒⠒⠒⠒⠒⠒⠀⠀⠒⠒⠒⠒⠒⠒⠒⠒⠒⠀⠀⠒⠒⠒⠒⠒⠒⠒⠒⠒⠒⠒⠒⠒⠒⠒⠒⠒⠒⠀⠀<-- underl. too long⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠚⠁⠝⠥⠁⠗⠀⠀⠀⠼⠁⠚⠚⠀⠀⠀⠀⠀⠀⠀⠼⠑⠚⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠋⠑⠃⠗⠥⠁⠗⠀⠀⠼⠓⠚⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠍⠜⠗⠵⠀⠀⠀⠀⠀⠼⠁⠃⠚⠀⠀⠀⠀⠀⠀⠀⠼⠉⠚⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠁⠏⠗⠊⠇⠀⠀⠀⠀⠼⠊⠚⠀⠀⠀⠀⠀⠀⠀⠀⠼⠁⠚⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
```

expected:

```
⠍⠕⠝⠁⠞⠀⠀⠀⠀⠑⠗⠎⠏⠁⠗⠝⠊⠎⠀⠀⠑⠗⠎⠏⠁⠗⠝⠊⠎⠀⠋⠑⠗⠊⠑⠝⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠒⠒⠒⠒⠒⠒⠒⠀⠀⠒⠒⠒⠒⠒⠒⠒⠒⠒⠀⠀⠒⠒⠒⠒⠒⠒⠒⠒⠒⠒⠒⠒⠒⠒⠒⠒⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠚⠁⠝⠥⠁⠗⠀⠀⠀⠼⠁⠚⠚⠀⠀⠀⠀⠀⠀⠀⠼⠑⠚⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠋⠑⠃⠗⠥⠁⠗⠀⠀⠼⠓⠚⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠍⠜⠗⠵⠀⠀⠀⠀⠀⠼⠁⠃⠚⠀⠀⠀⠀⠀⠀⠀⠼⠉⠚⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠁⠏⠗⠊⠇⠀⠀⠀⠀⠼⠊⠚⠀⠀⠀⠀⠀⠀⠀⠀⠼⠁⠚⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
```

it's not a bad error but not necessary⠀⠀⠀⠀⠀

**Comment by bertfrees** [comment]
OK thanks @mixa72!
