### ISSUE TITLE
[4.4:65] The system shall be able to render tables of contents, list of images, index, glossaries, etc. in a two-column format…

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#46]
### Requirement

[[4.4:65]](http://snaekobbi.github.io/requirements#4.4:65) The system shall be able to render tables of contents, list of images, index, glossaries, etc. in a two-column format with the entries on the left and other content such as page numbers aligned on the right. Optionally leaders may be used to connect the two columns.
### Tasks
- [ ] [[pipeline-mod-braille#17] Support leaders](https://github.com/snaekobbi/pipeline-mod-braille/issues/17)
- [ ] system tests
  - [x] @mixa72 ![PASS](http://snaekobbi.github.io/sprints/PASS.svg)
  - [x] @stesk ![PASS](http://snaekobbi.github.io/sprints/PASS.svg)
  - [ ] @JC-MTM, @BWestling ![Ready for test](http://snaekobbi.github.io/sprints/Ready_for_test.svg)
  - [x] @KariRudjord ![PASS](http://snaekobbi.github.io/sprints/PASS.svg)
  - [ ] @paivis ![Ready for test](http://snaekobbi.github.io/sprints/Ready_for_test.svg)
### Known issues
- [ ] [[obfl#31] Problem with leader](https://github.com/braillespecs/obfl/issues/31)
