### ISSUE TITLE
[4.4:66] The system shall support positioning of notes at the bottom of the page on which they are being referenced.

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#47]
### Requirement

[[4.4:66]](http://snaekobbi.github.io/requirements#4.4:66) The system shall support positioning of notes at the bottom of the page on which they are being referenced.
### Tasks
- [x] CSS support for Dotify footnotes (@bertfrees)
- [ ] finish CSS specification (@bertfrees)
- [x] implement CSS support (@bertfrees)
- [x] system tests
  - [x] @KariRudjord ![PASS](http://snaekobbi.github.io/sprints/PASS.svg)
  - [x] @stesk ![PASS](http://snaekobbi.github.io/sprints/PASS.svg)
  - [x] @mixa72 ![PASS](http://snaekobbi.github.io/sprints/PASS.svg)

**Comment by bertfrees** [comment]
I have given an explanation about how to use this feature in an email.
