### ISSUE TITLE
[4.4:67] The system shall support collecting of notes either at the end of each volume, or at the end of the entire book.

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#48]
### Requirement

[[4.4:67]](http://snaekobbi.github.io/requirements#4.4:67) The system shall support collecting of notes either at the end of each volume, or at the end of the entire book.
### Tasks
- [x] CSS support for volume (Dotify) endnotes (@bertfrees)
- [x] CSS support for chapter endnotes (@bertfrees)
- [ ] finish CSS specification (@bertfrees)
- [x] implement CSS support (@bertfrees)
  - [x] volume endnotes
  - [x] chapter endnotes
- [x] system tests
  - [x] @KariRudjord ![PASS](http://snaekobbi.github.io/sprints/PASS.svg)
  - [x] @stesk  ![PASS](http://snaekobbi.github.io/sprints/PASS.svg) (Only tested for end of volume)
  - [x] @mixa72 ![PASS](http://snaekobbi.github.io/sprints/PASS.svg)

**Comment by bertfrees** [comment]
@mixa72 asks if we can add "end-of-chapter notes" to the requirements. This should be pretty straightforward, at least if we don't have to deal with splitting note sections of chapters that are split over volumes.

@BWestling: OK to add?

**Comment by bertfrees** [comment]
I have given an explanation about how to use this feature in an email. End-of-chapter notes have also been implemented, and explained in an email to Mischa.
