### ISSUE TITLE
[4.4:74] The system shall support single and double line spacing.

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#55]
### Requirement

[[4.4:74]](http://snaekobbi.github.io/requirements#4.4:74) The system shall support single and double line spacing.
### Tasks
- [ ] finalise requirement: [[requirements#25] Tests for line spacing](https://github.com/snaekobbi/requirements/pull/25) (@bertfrees)
- [x] specification: [[braille-css-spec#18] Line spacing](https://github.com/snaekobbi/braille-css-spec/issues/18) (@jukkae, @bertfrees)
- [ ] implementation: [[pipeline-mod-braille#26] Support line spacing](https://github.com/snaekobbi/pipeline-mod-braille/issues/26) (@jukkae, @bertfrees)
- [x] ~~provide test data~~
- [x] ~~write test cases~~
- [x] ~~execute system tests~~
