### ISSUE TITLE
[4.5:78] The user shall have control over page breaking…

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#58]
### Requirement

[[4.5:78]](http://snaekobbi.github.io/requirements#4.5:78) The user shall have control over page breaking by means of
- inserting hard page breaks,
- protecting blocks from being split across multiple pages,
- avoiding page breaks within blocks leaving only the first line(s) on the first page (orphan control),
- avoiding page breaks within blocks leaving only the last line(s) on the second page (widow control), and
- keeping a block’s first line(s) on the same page as the preceding block.
### Tasks
- [x] specification
  - [x] OBFL: widows and orphans: http://files.pef-format.org/drafts/obfl/obfl-specification.html#L1023
- [ ] implementation
  - [ ] Fix keep and keep-with-next in Dotify (https://github.com/joeha480/dotify/issues/101)
  - [ ] Add support for widows and orphans in Dotify
- [x] example in braille CSS specification (@bertfrees): see http://snaekobbi.github.io/braille-css-spec/#controlling-page-breaks
- [ ] execute system tests
  - [x] @mixa72 ![FAIL](http://snaekobbi.github.io/sprints/FAIL.svg)
  - [x] @KariRudjord ![PASS](http://snaekobbi.github.io/sprints/PASS.svg)
  - [ ] @paivis ![Ready for test](http://snaekobbi.github.io/sprints/Ready_for_test.svg)
  - [x] @dkager ![PASS](http://snaekobbi.github.io/sprints/PASS.svg)
  - [x] @stesk ![FAIL](http://snaekobbi.github.io/sprints/FAIL.svg)
  - [x] @JC-MTM (MTM-script) ![FAIL](http://snaekobbi.github.io/sprints/FAIL.svg)
### Test results
- DE/DK: Widow/orphan control not working (known issue)
- NL: Only the very basic features have been tested, i.e. margins, header text (page numbers) and automatic page breaking.

**Comment by dkager** [comment]
Some comments based on the conversion at Dedicon.

Say you have the following CSS:

```
pagenum {
    display: page-break;
}
level1, level2, level3,
frontmatter, bodymatter, rearmatter {
    page-break-before: always;
    page-break-after: always;
}
```

There are a number of rules:
- On siblings, a forced `page-break-after` followed by a forced `page-break-before` should be collapsed as per these [rules](http://snaekobbi.github.io/braille-css-spec/master/index.html#page-breaking-rules).
- Forced page breaks after the last element with content should obviously be ignored. Duplex-printed books made of sheets of double-width paper that are folded down the middle are an exception, they can only end after a right page.
- If `display: page-break` will imply a forced page break this too should be collapsed with the above rule.
- Page breaking within sentences is allowed.
- Currently, even page breaking in the middle of a word is allowed, though it may be desirable to avoid this in the future. But this can probably be address in the input file and doesn't need special handling in the system.

**Comment by bertfrees** [comment]
Thanks Davy.

> - Currently, even page breaking in the middle of a word is allowed, though it may be desirable to avoid this in the future. But this can probably be address in the input file and doesn't need special handling in the system.

If with "page breaking" you mean print page breaking, yes then maybe it can be addressed in the input.

Here is a bit of background about `display: page-break`:

`display: page-break` is a leftover from the liblouisutdml based formatter, because in liblouisutdml print page breaks are a special feature. It should have really been called `print-page-break`. It is not officially documented in the CSS spec, and it is not supported by the Dotify based formatter.

Basically `display: page-break` was used for fulfilling requirements 4.8:105 + 4.8:107 + 4.7:102 (the print page numbers part). The two features were linked, it was all or nothing. However in the new system we want to support 105 and 107 separately. For example we may want to have the page numbers in the left margin instead of a line, but we still want to skip it when it's at the top or bottom of a page. Or we want a separator line which is rendered also at the top or bottom of a page.

Instead of a special value for `display`, which doesn't make that much sense anymore, I'm thinking of something else. Maybe a pseudo-class for matching elements that appear at a braille page transition.

Anyway, we will first look at requirements 105 and 106 before going to 107. The requirement that a print page break indicator should never appear at the bottom of a braille page can be easily achieved with `page-break-after:avoid`.

**Comment by dkager** [comment]
> If with "page breaking" you mean print page breaking, yes then maybe it can be addressed in the input.

Yes. But now that I think about it, page breaks inserted by the system to avoid page overflows should also not occur in the middle of words.

Maybe the problem of when to clear the print page string can be solved like this:
- If a pagenum appears on a braille page it is used for the header of that braille page, either alone or in a range.
- The last pagenum will carry on to the next braille pages. That is, a stand-alone pagenum will simply be kept (= not cleared), and from a range of page numbers only the last one is used.
- The end of a container clears the page number string (frontmatter, bodymatter, level, level1, etc).

The above also contains a new problem. On one braille page you can have 2 (or more) print pages, thus in the header we put a range of print page numbers. But then on the next braille page, if no new print page starts there, we want only the last encountered pagenum in the header.
To solve this you can set two strings, one (potential) range and one "last encountered" pagenum. You can then select the appropriate string based on the braille page, which is where the pseudo-class suggested above comes in handy. Does this make sense?

**Comment by bertfrees** [comment]
For selecting exactly which print page numbers to put in the header field, we can use several combinations of the following features:
- There will be an optional second argument of the CSS [string()](http://snaekobbi.github.io/braille-css-spec/#the-string-function) function (see https://github.com/snaekobbi/braille-css-spec/issues/17) to define the scope and search direction. E.g. `last` means "the current value" and `last-on-page` means the last value of the current page. There can even be special purpose values for creating page ranges.
- We can use different variables for different parts of the print page range, like you propose, and also like @joeha480 does in his xml-to-obfl step with "pagenum" and "pagenum-turn".
- We can use `text-transform` to post-process strings in header fields.

I'm not sure I understand how the pseudo-class comes into play in your proposal.

**Comment by jukkae** [comment]
Orphans now supported in OBFL specification -> css-to-obfl can already be modified. No pef output yet.
