### ISSUE TITLE
[4.5:80] The user shall have control over the page dimensions and the size of page margins.

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#60]
### Requirement

[[4.5:80]](http://snaekobbi.github.io/requirements#4.5:80) The user shall have control over the page dimensions and the size of page margins.
### Tasks
- [x] braille CSS specification (@bertfrees)
- [x] new implementation (@jukkae, @bertfrees)
- [x] example in braille CSS specification (@bertfrees): see http://snaekobbi.github.io/braille-css-spec/#h3_page-boxes
- [ ] execute system tests
  - [x] @mixa72 ![PASS](http://snaekobbi.github.io/sprints/PASS.svg)
  - [x] @KariRudjord ![PASS](http://snaekobbi.github.io/sprints/PASS.svg)
  - [ ] @paivis ![Ready for test](http://snaekobbi.github.io/sprints/Ready_for_test.svg)
  - [x] @dkager ![PASS](http://snaekobbi.github.io/sprints/PASS.svg)
  - [x] @stesk ![PASS](http://snaekobbi.github.io/sprints/PASS.svg)
  - [x] @JC-MTM (MTM-script) ![PASS](http://snaekobbi.github.io/sprints/PASS.svg)
### Test results
- NL: Only the very basic features have been tested, i.e. margins, header text (page numbers) and automatic page breaking.
