### ISSUE TITLE
[4.5:81] There shall be support for content in the header and footer of pages…

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#61]
### Requirement

[[4.5:81]](http://snaekobbi.github.io/requirements#4.5:81) There shall be support for content in the header and footer of pages. Content can be rendered in the left corner, the center and the right corner.
### Tasks
- [x] specification: Support multiple lines in header/footer
  - [x] OBFL (@joeha480)
  - [x] braille CSS (@bertfrees)
- [x] implementation
  - [x] Support multiple lines in header/footer
    - [x] Dotify: already supported
    - [x] css-to-obfl (@jukkae)
  - [x] Support spacing between the footer and the page content: can be accomplished with the multiple lines in footer feature in Dotify
- [x] example in braille CSS specification (@bertfrees): see http://snaekobbi.github.io/braille-css-spec/#h3_page-boxes
- [ ] execute system tests
  - [x] @mixa72 ![PASS](http://snaekobbi.github.io/sprints/PASS.svg)
  - [x] @KariRudjord ![PASS](http://snaekobbi.github.io/sprints/PASS.svg)
  - [ ] @paivis ![Ready for test](http://snaekobbi.github.io/sprints/Ready_for_test.svg)
  - [x] @dkager ![PASS](http://snaekobbi.github.io/sprints/PASS.svg)
  - [x] @stesk ![PASS](http://snaekobbi.github.io/sprints/PASS.svg)
  - [x] @JC-MTM (MTM-script)
### Test results
- DE: Print page range not working yet: see https://github.com/snaekobbi/sprints/issues/82
- SE: Pass for page alternating page numbering on left/right pages; fail for centered position of page numbering; fail for content of footing except for notes.
- NL: Only the very basic features have been tested, i.e. margins, header text (page numbers) and automatic page breaking.

**Comment by bertfrees** [comment]
@joeha480 Can you find out what the exact issues were with the tests for Swedish (fail for centered position of page numbering; fail for content of footing except for notes)? Are they known problems in the script or is it a problem with configuration?
