### ISSUE TITLE
[4.5:82] The header and footer layout shall be able to change between sections within the document.

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#62]
### Requirement

[[4.5:82]](http://snaekobbi.github.io/requirements#4.5:82) The header and footer layout shall be able to change between sections within the document.
### Tasks
- [x] example in braille CSS specification (@bertfrees): see http://snaekobbi.github.io/braille-css-spec/#h3_page-boxes
- [ ] execute system tests
  - [x] @mixa72 ![PASS](http://snaekobbi.github.io/sprints/PASS.svg)
  - [x] ~~@KariRudjord~~
  - [ ] @paivis ![Ready for test](http://snaekobbi.github.io/sprints/Ready_for_test.svg)
  - [x] ~~@dkager~~
  - [x] @stesk ![PASS](http://snaekobbi.github.io/sprints/PASS.svg)
  - [x] @JC-MTM (MTM-script)
### Test results
- DE: Print page range not working yet: see https://github.com/snaekobbi/sprints/issues/82
- SE: Pass for different page numbering in header in various sections of the document; fail for footer.

**Comment by bertfrees** [comment]
@joeha480 Can you find out what the exact issues were with the Swedish tests? Are they known problems in the script or is it a problem with configuration? @JC-MTM @BWestling You didn't attach any test data for this test (I think) so it's a bit stabbing in the dark for us.
