### ISSUE TITLE
[4.5:84] When printing double-sided, there shall be support for hard page breaks that jump to the next right- or left-hand page.

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#64]
### Requirement

[[4.5:84]](http://snaekobbi.github.io/requirements#4.5:84) When printing double-sided, there shall be support for hard page breaks that jump to the next right- or left-hand page.
### Tasks
- [x] implementation
  - [x] ~~Dotify~~
  - [x] css-to-obfl: jump to right-hand page can be accomplished with a new OBFL sequence, jump to left-hand page will not be supported for now
- [x] example in braille CSS specification (@bertfrees): see http://snaekobbi.github.io/braille-css-spec/#controlling-page-breaks
- [ ] execute system tests
  - [x] @mixa72 ![FAIL](http://snaekobbi.github.io/sprints/FAIL.svg)
  - [x] ~~@KariRudjord~~
  - [ ] @paivis ![Ready for test](http://snaekobbi.github.io/sprints/Ready_for_test.svg)
  - [x] ~~@dkager~~
  - [x] @stesk ![FAIL](http://snaekobbi.github.io/sprints/FAIL.svg)
  - [x] @JC-MTM (MTM-script)
### Test results
- DE/DK: Left not supported (known issue)

**Comment by bertfrees** [comment]
@joeha480 A use case for `page-break-before:left` just came to mind: if you want to have a table on facing pages, you need it to start in the top left corner of the page spread.

**Comment by bertfrees** [comment]
@JC-MTM @BWestling What was the issue exactly?
