### ISSUE TITLE
[4.5:85] When printing double-sided, the system shall allow the page layout to differ between left- and right-hand pages.

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#65]
### Requirement

[[4.5:85]](http://snaekobbi.github.io/requirements#4.5:85) When printing double-sided, the system shall allow the page layout (~~page margins as well as~~ header and footer layout) to differ between left- and right-hand pages.
### Tasks
- [x] example in braille CSS specification (@bertfrees): see http://snaekobbi.github.io/braille-css-spec/#h3_page-boxes
- [ ] execute system tests
  - [x] @mixa72 ![PASS](http://snaekobbi.github.io/sprints/PASS.svg)
  - [x] ~~@KariRudjord~~
  - [ ] @paivis ![Ready for test](http://snaekobbi.github.io/sprints/Ready_for_test.svg)
  - [x] ~~@dkager~~
  - [x] @stesk ![PASS](http://snaekobbi.github.io/sprints/PASS.svg)
  - [x] @JC-MTM ![PASS](http://snaekobbi.github.io/sprints/PASS.svg)
