### ISSUE TITLE
[4.6:88] The system shall be able to perform automatic volume breaking…

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#68]
### Requirement

[[4.6:88]](http://snaekobbi.github.io/requirements#4.6:88) The system shall be able to perform automatic volume breaking with constraints. It shall be possible to precisely tweak the algorithm. It shall take values for minimal and maximal number of pages per volume. It shall support special ranges for the first and last volume of sections. The algorithm shall take into account that certain points in the book are better suited for being the start of a new volume than other points and that certain sections belong in certain volumes.
## sprint#5 [:fast_forward:](https://github.com/snaekobbi/sprints/issues/149)

In this sprint we implement only basic volume breaking, with the only constraint being a maximal number of pages per volume.
### Tasks
- [ ] Support for basic volume splitting (as implemented in OBFL/Dotify) in CSS parser and CSS-to-OBFL (@dkager)
  - [ ] [[braille-css#10] Volume support](https://github.com/snaekobbi/braille-css/pull/10)
  - [ ] [[pipeline-mod-braille#13] Support volumes](https://github.com/snaekobbi/pipeline-mod-braille/issues/13)
