### ISSUE TITLE
[4.6:89] The system shall provide the possibility of repeating certain content in several volumes.

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#69]
### Requirement

[[4.6:89]](http://snaekobbi.github.io/requirements#4.6:89) The system shall provide the possibility of repeating certain content, such as title pages, in several volumes.
### Tasks
- [x] CSS specification
  - [x] [[braille-css-spec#23] Including and repeating content in specific volumes](https://github.com/snaekobbi/braille-css-spec/issues/23) (@bertfrees): see http://snaekobbi.github.io/braille-css-spec/#h3_named-flows
- [ ] Support in CSS parser and CSS-to-OBFL (@dkager)
  - [x] [[braille-css#10] Volume support](https://github.com/snaekobbi/braille-css/pull/10)
  - [ ] [[braille-css#12] ::alternate and ::duplicate](https://github.com/snaekobbi/braille-css/issues/12)
  - [ ] [[pipeline-mod-braille#13] Support volumes](https://github.com/snaekobbi/pipeline-mod-braille/issues/13)
  - [ ] [[daisy/pipeline-mod-braille#61] Support @volume](https://github.com/daisy/pipeline-mod-braille/pull/61)

**Comment by dkager** [comment]
Title pages are a bit tricky because they could be automatically generated and thus not easy to specify in CSS.
Besides those, is there any other content that needs to be repeated? Dedicon doesn't repeat the entire frontmatter for example, so I'd like to give #81 higher priority.

**Comment by bertfrees** [comment]
Whether the content that is to be repeated is automatically generated or not is not really relevant I think.

If the content is generated internally without the help of CSS, let's say with an XSLT, the most appropriate way to have it repeated in several volumes is still via CSS. The alternative is to produce the OBFL directly, but then you loose all CSS configurability. The CSS specification supports repeating content in specific volumes: see http://snaekobbi.github.io/braille-css-spec/#h3_named-flows.

Content could also be generated (partly) with the help of CSS, for example:
- Metadata could be extracted from the header and inserted in certain places using the `string-set` property and the `string()` function.
- The `content` property could support a new value `content(<uri>)` that would insert the external XML document pointed to by the relative URI.
- Certain types of lists such as tables of contents or end notes could be generated directly in CSS, thereby implicitly inserting it in certain volumes. See also https://github.com/snaekobbi/braille-css-spec/issues/10.

Beside title pages, other content that needs to be repeated could be a list of special symbols, tables of contents (see related requirements [4.6:90](http://snaekobbi.github.io/requirements/#4.6:90) and [4.6:91](http://snaekobbi.github.io/requirements/#4.6:91)), etc.

**Comment by bertfrees** [comment]
Including/repeating content present in the source XML, possibly generated in a pre-step, is already implemented for the most part in https://github.com/daisy/pipeline-mod-braille/pull/61 by the way. However has not been tested very thoroughly yet. Let's stick to the plan and finish this first, together with #70 and #71 (tables of contents), before moving on to #81. Tables of contents deserve a high priority I think.
