### ISSUE TITLE
[4.6:90] The system shall support trimming down of a table of contents to a volume-scope table of contents…

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#70]
### Requirement

[[4.6:90]](http://snaekobbi.github.io/requirements#4.6:90) The system shall support trimming down of a table of contents to a volume-scope table of contents that includes only the entries that reference items present in the current volume.
### Tasks
- [x] Enhance CSS spec to support some OBFL features (@bertfrees): see http://snaekobbi.github.io/braille-css-spec/master/obfl.html
- [ ] Support in CSS parser and CSS-to-OBFL (@dkager)
  - [ ] [[braille-css#10] Volume support](https://github.com/snaekobbi/braille-css/pull/10)
  - [ ] [[pipeline-mod-braille#13] Support volumes](https://github.com/snaekobbi/pipeline-mod-braille/issues/13)
