### ISSUE TITLE
[4.6:91] In the case of an extended table of contents that is not trimmed down, it shall be possible to group entries according to volume…

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#71]
### Requirement

[[4.6:91]](http://snaekobbi.github.io/requirements#4.6:91) In the case of an extended table of contents that is not trimmed down (e.g. in the first volume), it shall be possible to group entries according to volume and insert a heading before each group.
### Tasks
- [x] Enhance CSS spec to support some OBFL features (@bertfrees): see http://snaekobbi.github.io/braille-css-spec/master/obfl.html
- [ ] Support in CSS parser and CSS-to-OBFL (@dkager)
  - [ ] [[braille-css#10] Volume support](https://github.com/snaekobbi/braille-css/pull/10)
  - [ ] [[pipeline-mod-braille#13] Support volumes](https://github.com/snaekobbi/pipeline-mod-braille/issues/13)
