### ISSUE TITLE
[4.6:92] In the case of endnotes being collected at the end of a book, it shall be possible to group the notes according to volume…

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#72]
### Requirement

[[4.6:92]](http://snaekobbi.github.io/requirements#4.6:92) In the case of endnotes being collected at the end of a book, it shall be possible to group the notes according to volume and insert a heading before each group.
### Tasks
- [ ] CSS support for Dotify endnotes (@bertfrees)
- [ ] finish CSS specification (@bertfrees)
- [ ] support in OBFL/Dotify
- [ ] implement CSS support (@bertfrees)
- [ ] system tests
  - [ ] @mixa72 
  - [ ] @stesk 
  - [ ] @KariRudjord
