### ISSUE TITLE
[4.7:97] The system shall be able to perform automatic numbering of braille pages and volumes.

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#77]
### Requirement

[[4.7:97]](http://snaekobbi.github.io/requirements#4.7:97) The system shall be able to perform automatic numbering of braille pages and volumes.
## sprint#4 [:fast_forward:](https://github.com/snaekobbi/sprints/issues/145)

In this sprint we deal only with braille page numbers.
### Tasks
- [x] example in braille CSS specification (@bertfrees): see http://snaekobbi.github.io/braille-css-spec/#printing-counters-the-counter-function
- [x] execute system tests
  - [x] @mixa72 ![PASS](http://snaekobbi.github.io/sprints/PASS.svg)
  - [x] @stesk ![PASS](http://snaekobbi.github.io/sprints/PASS.svg)
  - [x] @dkager ![PASS](http://snaekobbi.github.io/sprints/PASS.svg)
