### ISSUE TITLE
[4.7:102] The system shall be able to evaluate certain variables and counters at so-called fields…

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#82]
### Requirement

[[4.7:102]](http://snaekobbi.github.io/requirements#4.7:102) The system shall be able to evaluate certain variables and counters at so-called "fields", for example on the title page or in the page header or footer. Supported variables shall include at least the current braille page number, the current print page number or range of print pages contained in the current braille page, the current volume number, the total number of volumes, the total number of braille pages or sheets contained in the current volume or book, the current chapter title, the current chapter number, and the date.
## sprint#4 [:fast_forward:](https://github.com/snaekobbi/sprints/issues/138)

In this sprint we deal with at least braille page numbering and print page numbering (possibly page range) in the header/footer in various required number formats.
### Tasks
- [ ] specification
  - [ ] [[braille-css-spec#17] Named strings](https://github.com/snaekobbi/braille-css-spec/issues/17): optional second argument to `string()` (@bertfrees)
  - [x] [[joeha480/obfl#24] marker-reference syntax needs to be more expressive](https://github.com/joeha480/obfl/issues/24) => see http://files.pef-format.org/drafts/obfl/obfl-specification.html#L683
- [ ] implementation
  - [ ] css-to-obfl (@bertfrees)
  - [ ] dotify
  - [x] https://github.com/joeha480/dotify/issues/116
  - [ ] https://github.com/joeha480/dotify/issues/118
- [ ] example in braille CSS specification (@bertfrees)
  - [x] braille page numbers
  - [x] print page numbers: see http://snaekobbi.github.io/braille-css-spec/#original-pagination
  - [ ] print page ranges
  - [ ] number formats
- [ ] execute system tests
  - [x] @mixa72 ![FAIL](http://snaekobbi.github.io/sprints/FAIL.svg)
  - [x] ~~@KariRudjord~~
  - [ ] @paivis ![Ready for test](http://snaekobbi.github.io/sprints/Ready_for_test.svg)
  - [x] @dkager ![PASS](http://snaekobbi.github.io/sprints/PASS.svg)
  - [x] @stesk ![FAIL](http://snaekobbi.github.io/sprints/FAIL.svg)
  - [x] @JC-MTM
### Test results
- DE/DK: Print page range not working yet (known issue)
- SE: Fail. We need to work on this, and talk to Joel. Support is available for some of the examples given: the current print page number or range of print pages contained in the current braille page (page numbering in header), the current volume number, the total number of volumes (on title page), the current chapter title, the current chapter number (in table of contents). (So why fail)?
- NL: Tested braille page number in page header.

**Comment by dkager** [comment]
Some comments based on the conversion at Dedicon.

### Print page numbers

If you have the print page number and braille page number in the header, and if the print page associated with a braille page does not have a pagenum, then that position in the header should be empty. This can happen for example if the frontmatter doesn't contain any pagenums.

Say you have the following CSS:

```
@page {
    @top-center {
        content: string(print-page);
    }
}
pagenum {
    string-set: print-page content();
}
```

Then this seems to mean a new braille page should initialize the print-page variable to the empty string. _But_ this doesn't hold when a print page continues across multiple braille pages. In that case every consecutive braille page should get the same print page number in the header. So the counter needs to be reset on print page transitions.

The pagenum should be taken out of the normal flow. This does not work yet. Setting `display: none` appears to also prevent the string from being set.

Ranges of print pages are rendered as `from - to`, where the only rule is that _to_ > _from_. Single print page numbers are obviously rendered by themselves. Thus the following are all valid print page representations:
- 30
- 30 - 31
- 30 - 40

### Braille page numbers

The braille page numbers are rendered in the top-right corner. The numbers should be right-aligned and have a right margin of a few spaces. The most straight-forward (naive) way to do this in CSS would probably look like:

```
@page {
    @top-right {
        margin-right: 2;
        text-align: right;
        content: counter(page);
    }
}
```

However, this is [not supported](http://snaekobbi.github.io/braille-css-spec/master/index.html#page-margin-boxes). The easy work-around is to append a fixed number of spaces to the content string.

**Comment by bertfrees** [comment]
>
> The easy work-around is to append a fixed number of spaces to the content string.

Yes, that's the solution. Not only easy but also clear and intuitive.

**Comment by bertfrees** [comment]
> If you have the print page number and braille page number in the header, and if the print page associated with a braille page does not have a pagenum, then that position in the header should be empty. 

I assume page transitions without a page number will be indicated somehow. E.g. with an empty pagenum element. So in that case wouldn't `pagenum { string-set: print-page content(); }` be all we need?

> The easy work-around is to append a fixed number of spaces to the content string.

Yes, that's the solution. Not only easy but also clear and intuitive.

**Comment by dkager** [comment]
Re print page transitions: Yes, that would most likely work, and if not you can clear the string on section changes as I said in #58.
