### ISSUE TITLE
[4.8:105] The system shall provide the possibility of rendering print page breaks as full lines across the width of the page…

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#85]
### Requirement

[[4.8:105]](http://snaekobbi.github.io/requirements#4.8:105) The system shall provide the possibility of rendering print page breaks as full lines across the width of the page, optionally with the page number of the new print page incorporated in the line. A line break is inserted first whenever a print page break indicator is rendered, and following text continues on the line below the indicator. In other words, the print page break is not taken out of the normal flow of the text in order not to lose precision.
### Tasks
- [x] example in braille CSS specification (@bertfrees): see http://snaekobbi.github.io/braille-css-spec/#original-pagination
- [ ] execute system tests
  - [x] @mixa72 ![PASS](http://snaekobbi.github.io/sprints/PASS.svg)
  - [x] ~~@KariRudjord~~
  - [ ] @paivis ![Ready for test](http://snaekobbi.github.io/sprints/Ready_for_test.svg)
  - [x] ~~@dkager~~
  - [x] @stesk ![PASS](http://snaekobbi.github.io/sprints/PASS.svg)
  - [x] @JC-MTM (MTM-script) ![FAIL](http://snaekobbi.github.io/sprints/FAIL.svg)
### Test results
- DE: Collapsing of page break lines not working (known issue): see https://github.com/snaekobbi/sprints/issues/87
- NL: Not implemented in Dedicon's CSS yet.

**Comment by bertfrees** [comment]
@joeha480 According to Jens/Björn the test failed, but is this even a requirement for the MTM script?

**Comment by JC-MTM** [comment]
This IS a requirement for the MTM script. However Joel has not had the time to work on the code for this, nor has he been assigned this task.
Do you need us to send another, updated, test protocol?

**Comment by bertfrees** [comment]
OK thanks, all I needed to know. An updated test protocol is only needed if you have additional test results/issues/comments/priorities.

**Comment by dkager** [comment]
Requirement clarification:
Dedicon wants the opposite; that is, to always render the print page number and never a line. This boils down to making the line optional. This can probably be accomplished by setting the line to consist of whitespace.

**Comment by dkager** [comment]
Looking at the relevant braille CSS I'm going to be a bit more specific still, for the sake of documentation if nothing else. What Dedicon uses:
1. Put the (range of) print page number(s) in the page header.
2. If (1) is a page range, also put the actual print page number at the exact location of the `<pagenum/>` if it is not the first thing on that page.

It looks like you can do either (1) or (2) but not both. I will gladly be proven wrong as this is definitely a requirement for NL.

**Comment by bertfrees** [comment]
You can do both (1) and (2) at the same time (except the print page range which will be implemented in this sprint). And the line can be omitted by just not creating it, no need to make a line of whitespace.

As agreed during the call, if you could provide me a test document and expected BRF which I can make into a unit test that would be great. Then you don't need to perform any system tests.

**Comment by dkager** [comment]
Since GitHub is stubborn and thinks XML files are evil I sent you an e-mail with the output we want for educational material. The BRF file uses the Dutch Braillo table:
- { means capital sign
- % means number sign

**Comment by bertfrees** [comment]
Thanks.

**Comment by dkager** [comment]
I have the following CSS:

```
@page {
    size: 35 28;
    @top-center {
        content: string(print-page);
    }
    @top-right {
        content: counter(page);
    }
}
pagenum {
    display: block;
    margin-top: 1;
    margin-bottom: 1;
    text-align: center;
    string-set: print-page content();
}
```

This works beautifully with the current version of the test server (in BRF):

```
                #D               #B

                #B


.HOOFDSTUK #A

.EERSTE ALINEA4

                #C

.TWEEDE ALINEA4
```

There is too much whitespace, but in principle it looks good. The only problem is that the topmost centered `#B` is redundant. There is a pagenum at that place in the DTBook, but it's also rendered in the top margin and so this particular pagenum shouldn't be shown. I don't think this can (easily) be specified in CSS.

Hopefully the above made sense! Bert, you already have the related DTBook in your mail.

**Comment by bertfrees** [comment]
Thanks Davy,

The whitespace issue should be fixed in the current version.

The issue with the redundant `#B` is an example of requirement [4.8:107](http://snaekobbi.github.io/requirements/v1.3/index.xhtml#4.8:107): "skipping print page breaks when no text precedes or follows on the same braille page". Currently this can indeed not be done with CSS yet. I have some ideas but I haven't pushed them further because after discussing it on the call it appeared that almost everybody would already be happy if print pages were rendered at the top of a new braille page rather than at the bottom of the previous page, and so the consensus was that the priority of this issue wasn't as high as the other pagination related issues.
