### ISSUE TITLE
[4.8:106] The system shall provide the possibility of rendering print page breaks as marks in the left margin, taking them out of the normal text flow…

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#86]
### Requirement

[[4.8:106]](http://snaekobbi.github.io/requirements#4.8:106) The system shall provide the possibility of rendering print page breaks as marks in the left margin, taking them out of the normal text flow so that text that follows the element can continue on the same line.
### Tasks
- [ ] specification
  - [ ] braille CSS
  - [ ] OBFL
- [ ] implementation
  - [ ] css-to-obfl
  - [ ] Dotify
- [ ] example in braille CSS specification (@bertfrees)
- [ ] execute system tests
  - [x] @mixa72 ![FAIL](http://snaekobbi.github.io/sprints/FAIL.svg)
  - [ ] @KariRudjord 
  - [ ] @paivis 
  - [ ] @dkager 
  - [ ] @stesk 
  - [x] @JC-MTM (MTM-script)

**Comment by bertfrees** [comment]
@joeha480 According to Jens/Björn the test failed, but is this even a requirement for the MTM script?
