### ISSUE TITLE
[4.8:107] The system shall support skipping print page breaks when no text precedes or follows on the same braille page.

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#87]
### Requirement

[[4.8:107]](http://snaekobbi.github.io/requirements#4.8:107) The system shall support skipping print page breaks when no text precedes or follows on the same braille page.
### Tasks
- [ ] specification
  - [ ] braille CSS
  - [ ] OBFL
- [ ] implementation
- [ ] example in braille CSS specification (@bertfrees)
- [ ] execute system tests
  - [x] @mixa72 ![FAIL](http://snaekobbi.github.io/sprints/FAIL.svg)
  - [ ] @KariRudjord 
  - [ ] @paivis 
  - [ ] @dkager 
  - [ ] @stesk 
  - [x] @JC-MTM (MTM-script)

**Comment by jukkae** [comment]
Note to self: Remember to test this, especially if no code changes are required (only CSS page-break-after: avoid)

**Comment by bertfrees** [comment]
@joeha480 According to Jens/Björn the test failed, but is this even a requirement for the MTM script?
