### ISSUE TITLE
[4.9:108] The system shall support templates for different products…

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#88]
### Requirement

[[4.9:108]](http://snaekobbi.github.io/requirements#4.9:108) The system shall support templates for different products, e.g. books vs. magazines.
### Tasks
- [x] continue implementation of templates in web UI (@josteinaj)
- [ ] system test
  - [x] @mixa72 ![PASS](http://snaekobbi.github.io/sprints/PASS.svg)
  - [x] @KariRudjord ![PASS](http://snaekobbi.github.io/sprints/PASS.svg)
  - [ ] @stesk ![Ready for test](http://snaekobbi.github.io/sprints/Ready_for_test.svg)
  - [x] @JC-MTM ![PASS](http://snaekobbi.github.io/sprints/PASS.svg)

**Comment by josteinaj** [comment]
What does this entail besides simply supporting templates? Is giving the templates a custom name enough?

**Comment by bertfrees** [comment]
Yeah, implementation-wise I don't think there is a difference between requirements 108 (for different products) and [109](https://github.com/snaekobbi/sprints/issues/89) (for different end user groups).

**Comment by josteinaj** [comment]
Ok, so just allowing custom names is enough then. Sounds good :). User groups would be a bigger job to add to the Web UI I think.

**Comment by bertfrees** [comment]
And [110](https://github.com/snaekobbi/sprints/issues/90): "be able to reuse templates" is a bit of a pleonasm.

**Comment by josteinaj** [comment]
Yeah, templates wouldn't be of much use if you can't (re)use them :).
