### ISSUE TITLE
[4.9:109] The system shall support templates for different end user groups.

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#89]
### Requirement

[[4.9:109]](http://snaekobbi.github.io/requirements#4.9:109) The system shall support templates for different end user groups.
### Tasks
- [x] continue implementation of templates in web UI (@josteinaj)
- [ ] system test
  - [x] @mixa72 ![PASS](http://snaekobbi.github.io/sprints/PASS.svg)
  - [x] @KariRudjord ![PASS](http://snaekobbi.github.io/sprints/PASS.svg)
  - [ ] @stesk ![Ready for test](http://snaekobbi.github.io/sprints/Ready_for_test.svg)
  - [x] @JC-MTM ![PASS](http://snaekobbi.github.io/sprints/PASS.svg)

**Comment by josteinaj** [comment]
So what is meant by this, is the requirement that the Web UI should support user groups, and templates should belong to a user group?

**Comment by bertfrees** [comment]
Answer is no. Being able to give a template a name and description in which you can specify the end user group is enough.

**Comment by josteinaj** [comment]
Perfect.

I think I misunderstood the issue first, "end user group" is of course the users of the library, not the users of the webui.
