### ISSUE TITLE
[4.9:110] Users shall be able to reuse templates.

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#90]
### Requirement

[[4.9:110]](http://snaekobbi.github.io/requirements#4.9:110) Users shall be able to reuse templates.
### Tasks
- [x] continue implementation of templates in web UI (@josteinaj)
- [x] system test
  - [x] @mixa72 ![PASS](http://snaekobbi.github.io/sprints/PASS.svg)
  - [x] @KariRudjord ![PASS](http://snaekobbi.github.io/sprints/PASS.svg)
  - [x] @stesk ![PASS](http://snaekobbi.github.io/sprints/PASS.svg)
  - [x] @JC-MTM ![PASS](http://snaekobbi.github.io/sprints/PASS.svg)

**Comment by josteinaj** [comment]
Currently I've implemented templates so that:
- normal users can only use their own templates, as well as public templates (which is the templates manually placed in a shared directory by some admin with access to the server).
- admins can use all templates from all users, as well as public templates

Should there in addition be a way for normal users to mark some of their templates as "shared" so that other users can use them? Or should it maybe just be a global setting saying whether or not normal users can use eachothers templates?

I'll have to give some thought to anonymous (not-logged-in) users as well...
