### ISSUE TITLE
[4.9:111] Certain users shall be able to create templates.

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#91]
### Requirement

[[4.9:111]](http://snaekobbi.github.io/requirements#4.9:111) Certain users shall be able to create templates.
### Tasks
- [x] continue implementation of templates in web UI (@josteinaj)
- [x] system test
  - [x] @mixa72 ![PASS](http://snaekobbi.github.io/sprints/PASS.svg)
  - [x] @KariRudjord ![PASS](http://snaekobbi.github.io/sprints/PASS.svg)
  - [x] @stesk ![PASS](http://snaekobbi.github.io/sprints/PASS.svg)
  - [x] @JC-MTM ![PASS](http://snaekobbi.github.io/sprints/PASS.svg)

**Comment by josteinaj** [comment]
Does this imply that not all users should be allowed to create templates?

**Comment by bertfrees** [comment]
Yes that was the idea initially. That admins would be the only ones that can create/modify/delete templates. But if you think about it there's no harm in letting users have their own private templates (or even sharing among each other, which kind of creates a peer-to-peer network).

**Comment by josteinaj** [comment]
Marking a user as "not allowed to create templates" would mean I need to add a field to the DB table, and create an option for it in admin settings. Should I implement that in this sprint you think, or is this functionality not necessary?

Sharing templates: I'll create some issues for this since it's kind of a separate issue.

**Comment by bertfrees** [comment]
Implement in this sprint: no, not essential.

Sharing templates: as long as admins can share templates.
